### ISSUE TITLE
Trust Party

### ISSUE THREAD

**Issue by Ianaguila1998s** [ffxivcode/AutoDuty#177]
How do you change trust party in the Auto Duty Menu? Currently unable to select or am not looking in the right place. 
![image](https://github.com/user-attachments/assets/d22c921a-cdda-4c31-9c0c-d20d708b87d3)

**Comment by erdelf** [comment]
well.. I would say you need to select the duty, but you seem to have a different issue entirely.
Can you look in /xllog ?

**Comment by neo-raven** [comment]
same is happening to me, first time i got to put three NPC but can't change nor select duty
![Uploading imagem_2024-08-08_172326120.png…]()

**Comment by neo-raven** [comment]
17:25:29.867 | ERR | [WindowSystem] Error during Draw(): AutoDuty
	System.Runtime.CompilerServices.SwitchExpressionException: Non-exhaustive switch expression failed to match its input.
	Unmatched value was NonCombat.
	   at <PrivateImplementationDetails>.ThrowSwitchExpressionException(Object unmatchedValue)
	   at AutoDuty.Managers.TrustManager.ResetTrustIfInvalid() in C:\OneDrive\Projects\VisualStudioProjects\AutoDuty\AutoDuty\Managers\TrustManager.cs:line 78
	   at AutoDuty.Windows.MainTab.Draw() in C:\OneDrive\Projects\VisualStudioProjects\AutoDuty\AutoDuty\Windows\MainTab.cs:line 371
	   at AutoDuty.Windows.MainWindow.EzTabBar(String id, String KoFiTransparent, String openTabName, ImGuiTabBarFlags flags, ValueTuple`4[] tabs) in C:\OneDrive\Projects\VisualStudioProjects\AutoDuty\AutoDuty\Windows\MainWindow.cs:line 318
	   at AutoDuty.Windows.MainWindow.Draw() in C:\OneDrive\Projects\VisualStudioProjects\AutoDuty\AutoDuty\Windows\MainWindow.cs:line 345
	   at Dalamud.Interface.Windowing.Window.DrawInternal(DalamudConfiguration configuration) in C:\goatsoft\companysecrets\dalamud\\Interface\Windowing\Window.cs:line 346

**Comment by erdelf** [comment]
right.. don't be on a gatherer or crafter.

**Comment by TheBananaIntheButt** [comment]
The same thing is happening to me as well. I selected a party and now can't change them see same screen.

**Comment by erdelf** [comment]
well if it's the exact same thing.. I gave the answer already.

**Comment by TheBananaIntheButt** [comment]
The don't be on crafter or gather? I'm not

**Comment by erdelf** [comment]
Well.. same thing from you then, need your /xllog info

**Comment by TheBananaIntheButt** [comment]
If I change jobs it lets me swap the cast but when I go back to job that has already selected them I cant change it

**Comment by TheBananaIntheButt** [comment]
So short term fix for anyone else is to swap to different job change party in menu then swap back and start it. I can swap to smn change cast then swap back to red mage and start it up. Since I didn't que with smn I can swap back to smn and change cast again., Anyjob I've changed the trust team with is now unable to change trust member

My log says the something as above 
Unmatched value was NonCombat.

**Comment by TheBananaIntheButt** [comment]
If it helps after completing a trust it lets you reselect them again, but if you leave mid trust it goes back to undetectable.

**Comment by neo-raven** [comment]
but I'm also not using craft/gather job, I was on Viper all the time, sorry for the delay I got home now I was at work

**Comment by neo-raven** [comment]
@TheBananaIntheButt This worked for now but the changed job is locked again so you have to use all the other jobs, eventually there won't be enough jobs XD need some fix

**Comment by adambennett55** [comment]
This has already been fixed and will be in the next release!
