### ISSUE TITLE
[Bug] The command /autoduty does not exists

### ISSUE THREAD

**Issue by PhoenixtheII** [ffxivcode/AutoDuty#395]
### What happened?

![image](https://github.com/user-attachments/assets/42f15a6b-1a5f-4f3d-bd11-5e62efa8a4e7)

### Version Number

0.0.155

### Steps to reproduce the error

Install 0.0.155, enter game, use /autoduty

### Relevant log output

```shell
14:03:00.886 | INF | [AutoDuty] Failed loading plugin
	System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
	 ---> Newtonsoft.Json.JsonSerializationException: Error setting value to 'DutyModeEnum' on 'AutoDuty.Windows.Configuration'.
	 ---> System.NullReferenceException: Object reference not set to an instance of an object.
	   at AutoDuty.AutoDuty.set_CurrentTerritoryContent(Content value) in /home/runner/work/AutoDuty/AutoDuty/AutoDuty/AutoDuty.cs:line 62
	   at AutoDuty.Windows.Configuration.set_DutyModeEnum(DutyMode value) in /home/runner/work/AutoDuty/AutoDuty/AutoDuty/Windows/Config.cs:line 44
	   at Newtonsoft.Json.Serialization.ExpressionValueProvider.SetValue(Object target, Object value)
	   --- End of inner exception stack trace ---
	   at Newtonsoft.Json.Serialization.ExpressionValueProvider.SetValue(Object target, Object value)
	   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
	   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
	   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
	   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
	   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
	   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
	   at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectType)
	   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
	   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
	   at Dalamud.Configuration.PluginConfigurations.LoadForType[T](String pluginName) in C:\goatsoft\companysecrets\dalamud\\Configuration\PluginConfigurations.cs:line 123
	   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
	   at System.Reflection.MethodBaseInvoker.InvokeDirectByRefWithFewArgs(Object obj, Span`1 copyOfArgs, BindingFlags invokeAttr)
	   --- End of inner exception stack trace ---
	   at System.Reflection.MethodBaseInvoker.InvokeDirectByRefWithFewArgs(Object obj, Span`1 copyOfArgs, BindingFlags invokeAttr)
	   at System.Reflection.MethodBaseInvoker.InvokeWithOneArg(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
	   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
	   at Dalamud.Plugin.DalamudPluginInterface.GetPluginConfig() in C:\goatsoft\companysecrets\dalamud\\Plugin\DalamudPluginInterface.cs:line 407
	   at AutoDuty.AutoDuty..ctor() in /home/runner/work/AutoDuty/AutoDuty/AutoDuty/AutoDuty.cs:line 193
14:03:00.886 | INF | [LOCALPLUGIN] Finished loading "AutoDuty"
```

**Comment by erdelf** [comment]
unload and load AD again.

**Comment by PhoenixtheII** [comment]
> unload and load AD again.

![image](https://github.com/user-attachments/assets/417f3a6d-8c35-496b-b6a9-b791a08cd014)

**Comment by Aimsucks** [comment]
Experiencing the same error. AutoDuty has no options to open any interface and no chat commands are working.

**Comment by erdelf** [comment]
So.. for everyone..

Just a temporary issue, cause has already been identified.

Current workaround is only enabling AD once you logged into a character.

**Comment by PhoenixtheII** [comment]
Full workaround:

1. Before running the game: delete the AutoDuty plugin folder from installedPlugins
2. Start the game
3. Login
4. Install AutoDuty again.

**Comment by PhoenixtheII** [comment]
Erdelf in discord: 

erdelf — Today at 2:33 PM
I know the issue
precisely
it tries to access your player at startup by accident

**Comment by Aimsucks** [comment]
This issue occurs every time you launch the game, so make sure to unload (disable) the plugin before you close the game or you will have to uninstall the plugin, restart, log in, and install it again.

**Comment by erdelf** [comment]
new update is out. Bug should be fixed
