### ISSUE TITLE
[Bug] Leveling Trust Loops not working

### ISSUE THREAD

**Issue by kari418** [ffxivcode/AutoDuty#399]
### What happened?

Hey Team:

Problem Statements:
- When using Trust with auto leveling enabled, the system doesn't requeue and loop.
- Upon exiting the instance after the first run, the stop and pause buttons are also dimmed out. 
- This was working as expected yesterday 2024-09-04, but after updating the plugin 2 hours ago, it no longer works. 

Steps taken to try to resolve:
- I have to disable and reenable the plugin to force it back into working for another single run. 
- I've disabled and pre-mid-post loop settings and blocks to see if that was the issue and no change. 
- My configuration for all settings/plugins matches the recommended options in the info sheet for setup

Please let me know what else I should do to test this for you to debug this issue, or if I'm fundamentally doing this incorrectly. 

### Version Number

v0.0.0.156

### Steps to reproduce the error

Select Duty Mode: Trust
Select Leveling Mode: Auto
Select a loop amount over 1

Other conditions that may factor:
Character Trusts are all sub 75, so only Holm Switch is available

### Relevant log output

```shell
12:24:15.387 | ERR | [WindowSystem] Error during Draw(): AutoDuty v0.0.0.156###Autoduty
	System.NullReferenceException: Object reference not set to an instance of an object.
	   at ECommons.GameHelpers.Player.get_Job() in /home/runner/work/AutoDuty/AutoDuty/ECommons/ECommons/GameHelpers/Player.cs:line 38
	   at AutoDuty.Windows.MainTab.Draw() in /home/runner/work/AutoDuty/AutoDuty/AutoDuty/Windows/MainTab.cs:line 371
	   at AutoDuty.Windows.MainWindow.EzTabBar(String id, String KoFiTransparent, String openTabName, ImGuiTabBarFlags flags, ValueTuple`4[] tabs) in /home/runner/work/AutoDuty/AutoDuty/AutoDuty/Windows/MainWindow.cs:line 390
	   at AutoDuty.Windows.MainWindow.Draw() in /home/runner/work/AutoDuty/AutoDuty/AutoDuty/Windows/MainWindow.cs:line 412
	   at Dalamud.Interface.Windowing.Window.DrawInternal(DalamudConfiguration configuration) in C:\goatsoft\companysecrets\dalamud\\Interface\Windowing\Window.cs:line 346
```

```
12:24:21.063 | ERR | [AutoDuty] Object reference not set to an instance of an object.
	   at AutoDuty.Helpers.TrustHelper.ClearCachedLevels(Content content) in /home/runner/work/AutoDuty/AutoDuty/AutoDuty/Helpers/TrustHelper.cs:line 190
	   at ECommons.Automation.LegacyTaskManager.TaskManager.<>c__DisplayClass37_0.<Enqueue>b__0() in /home/runner/work/AutoDuty/AutoDuty/ECommons/ECommons/Automation/LegacyTaskManager/TaskManager@Enqueue.cs:line 63
	   at ECommons.Automation.LegacyTaskManager.TaskManager.Tick(Object _) in /home/runner/work/AutoDuty/AutoDuty/ECommons/ECommons/Automation/LegacyTaskManager/TaskManager.cs:line 143
```
```


### Other relevant plugins installed

BossMod Reborn: v7.2.0.117
vnav: v0.0.0.41
autoretainer: v4.3.2.5
rot solver reborn: v7.0.5.48
deliveroo: v5.5

**Comment by kari418** [comment]
I was able to loop an unsynced raid just now, so this appears to possibly be Trust specific.

**Comment by kari418** [comment]
Additional logs after recreating issue again
```
14:31:34.542 | DBG | [AutoRetainer] Task <EnqueueWriteWhenPlayerAvailable>b__0_0 completed successfully
14:31:34.772 | DBG | [BossModReborn] Condition change: BetweenAreas=False
14:31:34.772 | DBG | [BossModReborn] Condition change: BetweenAreas51=False
14:31:34.829 | DBG | [AutoDuty] SchedulerHelper - Executing action RecentlyWatchedCutsceneTimer
14:31:34.829 | DBG | [AutoDuty] SchedulerHelper - RecentlyWatchedCutsceneTimer Removed from Scheduler
14:31:34.913 | DBG | [AutoDuty] Task Loop-WaitPlayerReady completed successfully
14:31:34.913 | DBG | [AutoDuty] SchedulerHelper - Executing action OpenOverlay
14:31:34.913 | DBG | [AutoDuty] SchedulerHelper - OpenOverlay Removed from Scheduler
14:31:34.913 | DBG | [AutoDuty] TrustHelper - Opening Dawn
14:31:34.929 | DBG | [AutoDuty] Starting to execute task: Loop-WaitTimeBeforeAfterLoopActionsActionSet
14:31:34.929 | DBG | [AutoDuty] SchedulerHelper - ExitDutyTimeOut Removed from Scheduler
14:31:34.930 | INF | [AutoDuty] ExitDuty Finished
14:31:34.946 | DBG | [AutoDuty] Task Loop-WaitTimeBeforeAfterLoopActionsActionSet completed successfully
14:31:34.963 | DBG | [AutoDuty] Starting to execute task: EzThrottler.Throttle(Loop-WaitTimeBeforeAfterLoopActions, 5000)
14:31:34.979 | DBG | [AutoDuty] Task EzThrottler.Throttle(Loop-WaitTimeBeforeAfterLoopActions, 5000) completed successfully
14:31:34.996 | DBG | [AutoDuty] Starting to execute task: EzThrottler.Check(Loop-WaitTimeBeforeAfterLoopActions)
14:31:35.396 | DBG | [AutoDuty] TrustHelper - Opening Expansion: 5
14:31:35.413 | DBG | [AutoDuty] TrustHelper - Setting Krile level to 91
14:31:35.413 | INF | [AutoDuty] TrustHelper - Done getting trust levels for expansion 5
14:31:39.997 | DBG | [AutoDuty] Task EzThrottler.Check(Loop-WaitTimeBeforeAfterLoopActions) completed successfully
14:31:40.014 | DBG | [AutoDuty] Starting to execute task: Loop-AfterLoopActionsSetAction
14:31:40.031 | DBG | [AutoDuty] Task Loop-AfterLoopActionsSetAction completed successfully
14:31:40.047 | DBG | [AutoDuty] Starting to execute task: TrustLeveling-Debug
14:31:40.064 | DBG | [AutoDuty] Trust Leveling Enabled
14:31:40.064 | DBG | [AutoDuty] Task TrustLeveling-Debug completed successfully
14:31:40.081 | DBG | [AutoDuty] Starting to execute task: TrustLeveling-ClearCachedLevels
14:31:40.098 | ERR | [AutoDuty] Object reference not set to an instance of an object.
	   at AutoDuty.Helpers.TrustHelper.ClearCachedLevels(Content content) in /home/runner/work/AutoDuty/AutoDuty/AutoDuty/Helpers/TrustHelper.cs:line 190
	   at ECommons.Automation.LegacyTaskManager.TaskManager.<>c__DisplayClass37_0.<Enqueue>b__0() in /home/runner/work/AutoDuty/AutoDuty/ECommons/ECommons/Automation/LegacyTaskManager/TaskManager@Enqueue.cs:line 63
	   at ECommons.Automation.LegacyTaskManager.TaskManager.Tick(Object _) in /home/runner/work/AutoDuty/AutoDuty/ECommons/ECommons/Automation/LegacyTaskManager/TaskManager.cs:line 143
14:31:40.114 | DBG | [AutoDuty] Starting to execute task: TrustLeveling-GetLevels
14:31:40.131 | DBG | [AutoDuty] Get Trust Levels: our content was null, returning
14:31:40.131 | DBG | [AutoDuty] Task TrustLeveling-GetLevels completed successfully
14:31:40.149 | DBG | [AutoDuty] Starting to execute task: EzThrottler.Throttle(ECommonsGenericDelay, 50)
14:31:40.164 | DBG | [AutoDuty] Task EzThrottler.Throttle(ECommonsGenericDelay, 50) completed successfully
14:31:40.181 | DBG | [AutoDuty] Starting to execute task: EzThrottler.Check(ECommonsGenericDelay)
14:31:40.231 | DBG | [AutoDuty] Task EzThrottler.Check(ECommonsGenericDelay) completed successfully
14:31:40.247 | DBG | [AutoDuty] Starting to execute task: TrustLeveling-RecheckingTrustLevels
14:31:40.264 | DBG | [AutoDuty] Task TrustLeveling-RecheckingTrustLevels completed successfully
14:31:40.281 | DBG | [AutoDuty] Starting to execute task: Loop-CheckStopLoop
14:31:40.301 | DBG | [AutoDuty] Task Loop-CheckStopLoop completed successfully
```

**Comment by Herculezz55** [comment]
Looking at these logs it looks like something is clearing your CurrentTerritoryContent before Leveling helper is able to do its thing. First of all I need to add null check in there, but that's beside the point as it won't fix the issue, we need to determine what is clearing the Content on loop. I will investigate further.
