### ISSUE TITLE
[Bug] AD does not requeue when using Support & Auto Mode Disabled

### ISSUE THREAD

**Issue by Cryotechnic** [ffxivcode/AutoDuty#406]
### What happened?

Upon selecting "Support" for Duty Mode and not selecting anything for Leveling Mode (`None`), and specifying a custom number of loops, AD will select and queue for the dungeon correctly the first time, but will fail to do so on subsequent loops.

Observed queue failures: Porta Ducumana, Aetherochemical Research Facility

### Version Number

0.0.0.157

### Steps to reproduce the error

1- Select "Support" as the Duty Mode.
2- Do not select any mode for the Leveling Mode (`None`)
3- Specify an arbitrary number of loops
4- Select a Duty from the list of Supported Duties
5- Click `Run`
6- Wait until the duty is completed and your character exits the duty successfully

### Relevant log output

```shell
2024-09-06 13:34:19.566 -04:00 [ERR] [WindowSystem] Error during Draw(): AutoDuty v0.0.0.157###Autoduty
System.NullReferenceException: Object reference not set to an instance of an object.
   at ECommons.GameHelpers.Player.get_Job() in /home/runner/work/AutoDuty/AutoDuty/ECommons/ECommons/GameHelpers/Player.cs:line 38
   at AutoDuty.Windows.MainTab.Draw() in /home/runner/work/AutoDuty/AutoDuty/AutoDuty/Windows/MainTab.cs:line 453
   at AutoDuty.Windows.MainWindow.EzTabBar(String id, String KoFiTransparent, String openTabName, ImGuiTabBarFlags flags, ValueTuple`4[] tabs) in /home/runner/work/AutoDuty/AutoDuty/AutoDuty/Windows/MainWindow.cs:line 390
   at AutoDuty.Windows.MainWindow.Draw() in /home/runner/work/AutoDuty/AutoDuty/AutoDuty/Windows/MainWindow.cs:line 412
   at Dalamud.Interface.Windowing.Window.DrawInternal(DalamudConfiguration configuration) in C:\goatsoft\companysecrets\dalamud\\Interface\Windowing\Window.cs:line 346
2024-09-06 13:34:19.578 -04:00 [INF] LASTEXCEPTION:eyJXaGVuIjoiMjAyNC0wOS0wNlQxMzozNDoxOS41Nzg4NDk5LTA0OjAwIiwiSW5mbyI6IlN5c3RlbS5OdWxsUmVmZXJlbmNlRXhjZXB0aW9uOiBPYmplY3QgcmVmZXJlbmNlIG5vdCBzZXQgdG8gYW4gaW5zdGFuY2Ugb2YgYW4gb2JqZWN0LlxyXG4gICBhdCBFQ29tbW9ucy5HYW1lSGVscGVycy5QbGF5ZXIuZ2V0X0pvYigpIGluIC9ob21lL3J1bm5lci93b3JrL0F1dG9EdXR5L0F1dG9EdXR5L0VDb21tb25zL0VDb21tb25zL0dhbWVIZWxwZXJzL1BsYXllci5jczpsaW5lIDM4XHJcbiAgIGF0IEF1dG9EdXR5LldpbmRvd3MuTWFpblRhYi5EcmF3KCkgaW4gL2hvbWUvcnVubmVyL3dvcmsvQXV0b0R1dHkvQXV0b0R1dHkvQXV0b0R1dHkvV2luZG93cy9NYWluVGFiLmNzOmxpbmUgNDUzXHJcbiAgIGF0IEF1dG9EdXR5LldpbmRvd3MuTWFpbldpbmRvdy5FelRhYkJhcihTdHJpbmcgaWQsIFN0cmluZyBLb0ZpVHJhbnNwYXJlbnQsIFN0cmluZyBvcGVuVGFiTmFtZSwgSW1HdWlUYWJCYXJGbGFncyBmbGFncywgVmFsdWVUdXBsZWA0W10gdGFicykgaW4gL2hvbWUvcnVubmVyL3dvcmsvQXV0b0R1dHkvQXV0b0R1dHkvQXV0b0R1dHkvV2luZG93cy9NYWluV2luZG93LmNzOmxpbmUgMzkwXHJcbiAgIGF0IEF1dG9EdXR5LldpbmRvd3MuTWFpbldpbmRvdy5EcmF3KCkgaW4gL2hvbWUvcnVubmVyL3dvcmsvQXV0b0R1dHkvQXV0b0R1dHkvQXV0b0R1dHkvV2luZG93cy9NYWluV2luZG93LmNzOmxpbmUgNDEyXHJcbiAgIGF0IERhbGFtdWQuSW50ZXJmYWNlLldpbmRvd2luZy5XaW5kb3cuRHJhd0ludGVybmFsKERhbGFtdWRDb25maWd1cmF0aW9uIGNvbmZpZ3VyYXRpb24pIGluIEM6XFxnb2F0c29mdFxcY29tcGFueXNlY3JldHNcXGRhbGFtdWRcXFxcSW50ZXJmYWNlXFxXaW5kb3dpbmdcXFdpbmRvdy5jczpsaW5lIDM0NiIsIkNvbnRleHQiOiJbV2luZG93U3lzdGVtXSBFcnJvciBkdXJpbmcgRHJhdygpOiBBdXRvRHV0eSB2MC4wLjAuMTU3IyMjQXV0b2R1dHkifQ==
2024-09-06 13:34:19.578 -04:00 [ERR] [WindowSystem] Error during Draw(): AutoDuty v0.0.0.157###Autoduty
System.NullReferenceException: Object reference not set to an instance of an object.
   at ECommons.GameHelpers.Player.get_Job() in /home/runner/work/AutoDuty/AutoDuty/ECommons/ECommons/GameHelpers/Player.cs:line 38
   at AutoDuty.Windows.MainTab.Draw() in /home/runner/work/AutoDuty/AutoDuty/AutoDuty/Windows/MainTab.cs:line 453
   at AutoDuty.Windows.MainWindow.EzTabBar(String id, String KoFiTransparent, String openTabName, ImGuiTabBarFlags flags, ValueTuple`4[] tabs) in /home/runner/work/AutoDuty/AutoDuty/AutoDuty/Windows/MainWindow.cs:line 390
   at AutoDuty.Windows.MainWindow.Draw() in /home/runner/work/AutoDuty/AutoDuty/AutoDuty/Windows/MainWindow.cs:line 412
   at Dalamud.Interface.Windowing.Window.DrawInternal(DalamudConfiguration configuration) in C:\goatsoft\companysecrets\dalamud\\Interface\Windowing\Window.cs:line 346
2024-09-06 13:34:19.592 -04:00 [INF] LASTEXCEPTION:eyJXaGVuIjoiMjAyNC0wOS0wNlQxMzozNDoxOS41OTI5NTEzLTA0OjAwIiwiSW5mbyI6IlN5c3RlbS5OdWxsUmVmZXJlbmNlRXhjZXB0aW9uOiBPYmplY3QgcmVmZXJlbmNlIG5vdCBzZXQgdG8gYW4gaW5zdGFuY2Ugb2YgYW4gb2JqZWN0LlxyXG4gICBhdCBFQ29tbW9ucy5HYW1lSGVscGVycy5QbGF5ZXIuZ2V0X0pvYigpIGluIC9ob21lL3J1bm5lci93b3JrL0F1dG9EdXR5L0F1dG9EdXR5L0VDb21tb25zL0VDb21tb25zL0dhbWVIZWxwZXJzL1BsYXllci5jczpsaW5lIDM4XHJcbiAgIGF0IEF1dG9EdXR5LldpbmRvd3MuTWFpblRhYi5EcmF3KCkgaW4gL2hvbWUvcnVubmVyL3dvcmsvQXV0b0R1dHkvQXV0b0R1dHkvQXV0b0R1dHkvV2luZG93cy9NYWluVGFiLmNzOmxpbmUgNDUzXHJcbiAgIGF0IEF1dG9EdXR5LldpbmRvd3MuTWFpbldpbmRvdy5FelRhYkJhcihTdHJpbmcgaWQsIFN0cmluZyBLb0ZpVHJhbnNwYXJlbnQsIFN0cmluZyBvcGVuVGFiTmFtZSwgSW1HdWlUYWJCYXJGbGFncyBmbGFncywgVmFsdWVUdXBsZWA0W10gdGFicykgaW4gL2hvbWUvcnVubmVyL3dvcmsvQXV0b0R1dHkvQXV0b0R1dHkvQXV0b0R1dHkvV2luZG93cy9NYWluV2luZG93LmNzOmxpbmUgMzkwXHJcbiAgIGF0IEF1dG9EdXR5LldpbmRvd3MuTWFpbldpbmRvdy5EcmF3KCkgaW4gL2hvbWUvcnVubmVyL3dvcmsvQXV0b0R1dHkvQXV0b0R1dHkvQXV0b0R1dHkvV2luZG93cy9NYWluV2luZG93LmNzOmxpbmUgNDEyXHJcbiAgIGF0IERhbGFtdWQuSW50ZXJmYWNlLldpbmRvd2luZy5XaW5kb3cuRHJhd0ludGVybmFsKERhbGFtdWRDb25maWd1cmF0aW9uIGNvbmZpZ3VyYXRpb24pIGluIEM6XFxnb2F0c29mdFxcY29tcGFueXNlY3JldHNcXGRhbGFtdWRcXFxcSW50ZXJmYWNlXFxXaW5kb3dpbmdcXFdpbmRvdy5jczpsaW5lIDM0NiIsIkNvbnRleHQiOiJbV2luZG93U3lzdGVtXSBFcnJvciBkdXJpbmcgRHJhdygpOiBBdXRvRHV0eSB2MC4wLjAuMTU3IyMjQXV0b2R1dHkifQ==
2024-09-06 13:34:19.592 -04:00 [ERR] [WindowSystem] Error during Draw(): AutoDuty v0.0.0.157###Autoduty
System.NullReferenceException: Object reference not set to an instance of an object.
   at ECommons.GameHelpers.Player.get_Job() in /home/runner/work/AutoDuty/AutoDuty/ECommons/ECommons/GameHelpers/Player.cs:line 38
   at AutoDuty.Windows.MainTab.Draw() in /home/runner/work/AutoDuty/AutoDuty/AutoDuty/Windows/MainTab.cs:line 453
   at AutoDuty.Windows.MainWindow.EzTabBar(String id, String KoFiTransparent, String openTabName, ImGuiTabBarFlags flags, ValueTuple`4[] tabs) in /home/runner/work/AutoDuty/AutoDuty/AutoDuty/Windows/MainWindow.cs:line 390
   at AutoDuty.Windows.MainWindow.Draw() in /home/runner/work/AutoDuty/AutoDuty/AutoDuty/Windows/MainWindow.cs:line 412
   at Dalamud.Interface.Windowing.Window.DrawInternal(DalamudConfiguration configuration) in C:\goatsoft\companysecrets\dalamud\\Interface\Windowing\Window.cs:line 346
2024-09-06 13:34:20.082 -04:00 [INF] [AutoDuty] ExitDuty Finished
2024-09-06 13:34:22.943 -04:00 [INF] [MareSynchronos] [Player...actory]{2} Building character data for Player took 37.8547ms
2024-09-06 13:34:23.009 -04:00 [INF] [MareSynchronos] [Player...actory]{2} Building character data for Pet took 31.3992ms
2024-09-06 13:34:49.741 -04:00 [WRN] [HITCH] Long FrameworkUpdate detected, 144.9017ms > 50ms - check in the plugin stats window.
2024-09-06 13:43:47.274 -04:00 [ERR] Exception during raise of Void <InvokeSafely>b__0()
System.NullReferenceException: Object reference not set to an instance of an object.
   at AutoDuty.Helpers.QueueHelper.QueueSupport() in /home/runner/work/AutoDuty/AutoDuty/AutoDuty/Helpers/QueueHelper.cs:line 134
   at AutoDuty.Helpers.QueueHelper.QueueUpdate(IFramework _) in /home/runner/work/AutoDuty/AutoDuty/AutoDuty/Helpers/QueueHelper.cs:line 235
   at Dalamud.Utility.EventHandlerExtensions.HandleInvoke(Action act) in C:\goatsoft\companysecrets\dalamud\\Utility\EventHandlerExtensions.cs:line 124
```

### Other relevant plugins installed

```
✅ AutoDuty - 0.0.0.157 (Loaded)
✅ BossMod Reborn - 7.2.0.118 (Loaded)
✅ Rotation Solver Reborn - 7.0.5.48 (Loaded)
✅ vnavmesh - 0.0.0.41 (Loaded)

**Comment by Herculezz55** [comment]
ok so this isn't the relevant log, i know errors make it look that way but thats just a Draw error, wont actually affect the operation of the plugin and was only happening during zoning, that said it will be fixed in next version and can hopefully allow for a better log

**Comment by Herculezz55** [comment]
Any updates on this with new logs? With newest version?

**Comment by Herculezz55** [comment]
Closing due to inactivity
