### ISSUE TITLE
ClickLib fork needs an update

### ISSUE THREAD

**Issue by SuspiciousActivity** [ffxivcode/AutoDuty#44]
My logs are getting spammed with this error:
```
2024-07-06 19:10:24.911 +02:00 [ERR] [AddonLifecycle] Exception in OnAddonUpdate during PostUpdate invoke.
System.MissingMethodException: Method not found: 'FFXIVClientStructs.FFXIV.Component.GUI.AtkStage* FFXIVClientStructs.FFXIV.Component.GUI.AtkStage.GetSingleton()'.
   at ClickLib.Bases.ClickBase`2.ClickAddonStage(UInt32 which, EventType type)
   at Dalamud.Game.Addon.Lifecycle.AddonLifecycle.InvokeListenersSafely(AddonEvent eventType, AddonArgs args, String blame) in C:\goatsoft\companysecrets\dalamud\Game\Addon\Lifecycle\AddonLifecycle.cs:line 165
```

Your fork of ClientLib needs an update, the original repo already has a [new commit](https://github.com/ffxivcode/ClickLib/commit/a5f5809dfcc628a92e19b35cb2534efca9075aad).

**Comment by adambennett55** [comment]
v51
