### ISSUE TITLE
[Bug] Worqor Zormor. Issues with 2nd boss to 3rd boss pathing

### ISSUE THREAD

**Issue by nicuity** [ffxivcode/AutoDuty#444]
### What happened?

After killing second boss, pathing seems to 'force' itself straight to the 1st and 2nd treasure chests. If it gets into combat it will not "wait for combat". Instead it will force itself on the MoveTo| command. RSR will keep my character in melee range but at the same time the pathing is trying to force its way so it's essentially a tug of war. My character will be attacking but also running to the next waypoint at the same time.
![ad](https://github.com/user-attachments/assets/2a3b9be3-31b0-4b37-8306-991a8202d6f4)
As you can see in the screenshot, pathing is forcing itself and is running my character into the wall. 

When this bug occurs, it once it kills the pack right before the third boss, it starts pathing BACK to the second boss and back again.

EDIT:

Got 2 more screenshots. First shows again it's not "waiting for combat" and is instead forcing pathing. RSR keeps it in melee and is in a tug of war with pathing.

![ad2](https://github.com/user-attachments/assets/20f714dc-b177-494d-a544-bd4d39a10089)

Next screenshot shows it pathing back to the 2nd boss after killing the pack right before third boss. As can be seen by the log, it says the pathing is complete but does not record this.

![ad3](https://github.com/user-attachments/assets/71fa3dea-77fc-4d0e-b93e-9811fae36941)

### Version Number

0.0.0.160

### Steps to reproduce the error

Trusts, auto leveling. Worqor Zormor right after 2nd boss. I've already tried rebuilding vnash as well as restarting the game.

### Relevant log output

```shell
19:00:06.632 | INF | [vnavmesh] Pathfinding complete
19:00:07.680 | INF | [AutoDuty] Starting Action Boss: Kahderyor
19:00:07.724 | INF | [vnavmesh] Queueing move-to <-53.210, 323.000, -57.420>
19:00:07.767 | INF | [vnavmesh] Pathfinding complete
19:00:09.882 | WRN | "XIVSlothCombo" is accessing "ObjectTable" outside the main thread. This is deprecated.
19:00:12.463 | ERR | [Avarice] Object reference not set to an instance of an object.
19:00:12.463 | ERR | [Avarice]    at ECommons.Reflection.ReflectionHelper.CallStatic(Object obj, String type, String name, Object[] values) in D:\VS\Avarice\ECommons\ECommons\Reflection\ReflectionHelper\CallStatic.cs:line 20
	   at Avarice.VfxEditorManager.RemoveVfx() in D:\VS\Avarice\Avarice\VfxEditorManager.cs:line 26
19:00:22.410 | ERR | [Avarice] Object reference not set to an instance of an object.
19:00:22.410 | ERR | [Avarice]    at ECommons.Reflection.ReflectionHelper.CallStatic(Object obj, String type, String name, Object[] values) in D:\VS\Avarice\ECommons\ECommons\Reflection\ReflectionHelper\CallStatic.cs:line 20
	   at Avarice.VfxEditorManager.RemoveVfx() in D:\VS\Avarice\Avarice\VfxEditorManager.cs:line 26
19:00:24.925 | ERR | [Avarice] Object reference not set to an instance of an object.
19:00:24.925 | ERR | [Avarice]    at ECommons.Reflection.ReflectionHelper.CallStatic(Object obj, String type, String name, Object[] values) in D:\VS\Avarice\ECommons\ECommons\Reflection\ReflectionHelper\CallStatic.cs:line 20
	   at Avarice.VfxEditorManager.RemoveVfx() in D:\VS\Avarice\Avarice\VfxEditorManager.cs:line 26
19:00:38.008 | ERR | [Avarice] Object reference not set to an instance of an object.
19:00:38.008 | ERR | [Avarice]    at ECommons.Reflection.ReflectionHelper.CallStatic(Object obj, String type, String name, Object[] values) in D:\VS\Avarice\ECommons\ECommons\Reflection\ReflectionHelper\CallStatic.cs:line 20
	   at Avarice.VfxEditorManager.RemoveVfx() in D:\VS\Avarice\Avarice\VfxEditorManager.cs:line 26
19:00:39.902 | WRN | "XIVSlothCombo" is accessing "ObjectTable" outside the main thread. This is deprecated.
19:00:50.254 | ERR | [Avarice] Object reference not set to an instance of an object.
19:00:50.254 | ERR | [Avarice]    at ECommons.Reflection.ReflectionHelper.CallStatic(Object obj, String type, String name, Object[] values) in D:\VS\Avarice\ECommons\ECommons\Reflection\ReflectionHelper\CallStatic.cs:line 20
	   at Avarice.VfxEditorManager.RemoveVfx() in D:\VS\Avarice\Avarice\VfxEditorManager.cs:line 26
19:01:00.172 | ERR | [Avarice] Object reference not set to an instance of an object.
19:01:00.172 | ERR | [Avarice]    at ECommons.Reflection.ReflectionHelper.CallStatic(Object obj, String type, String name, Object[] values) in D:\VS\Avarice\ECommons\ECommons\Reflection\ReflectionHelper\CallStatic.cs:line 20
	   at Avarice.VfxEditorManager.RemoveVfx() in D:\VS\Avarice\Avarice\VfxEditorManager.cs:line 26
19:01:02.620 | ERR | [Avarice] Object reference not set to an instance of an object.
19:01:02.620 | ERR | [Avarice]    at ECommons.Reflection.ReflectionHelper.CallStatic(Object obj, String type, String name, Object[] values) in D:\VS\Avarice\ECommons\ECommons\Reflection\ReflectionHelper\CallStatic.cs:line 20
	   at Avarice.VfxEditorManager.RemoveVfx() in D:\VS\Avarice\Avarice\VfxEditorManager.cs:line 26
19:01:11.908 | WRN | "XIVSlothCombo" is accessing "ObjectTable" outside the main thread. This is deprecated.
19:01:22.328 | ERR | [Avarice] Object reference not set to an instance of an object.
19:01:22.328 | ERR | [Avarice]    at ECommons.Reflection.ReflectionHelper.CallStatic(Object obj, String type, String name, Object[] values) in D:\VS\Avarice\ECommons\ECommons\Reflection\ReflectionHelper\CallStatic.cs:line 20
	   at Avarice.VfxEditorManager.RemoveVfx() in D:\VS\Avarice\Avarice\VfxEditorManager.cs:line 26
19:01:32.254 | ERR | [Avarice] Object reference not set to an instance of an object.
19:01:32.254 | ERR | [Avarice]    at ECommons.Reflection.ReflectionHelper.CallStatic(Object obj, String type, String name, Object[] values) in D:\VS\Avarice\ECommons\ECommons\Reflection\ReflectionHelper\CallStatic.cs:line 20
	   at Avarice.VfxEditorManager.RemoveVfx() in D:\VS\Avarice\Avarice\VfxEditorManager.cs:line 26
19:01:34.724 | ERR | [Avarice] Object reference not set to an instance of an object.
19:01:34.724 | ERR | [Avarice]    at ECommons.Reflection.ReflectionHelper.CallStatic(Object obj, String type, String name, Object[] values) in D:\VS\Avarice\ECommons\ECommons\Reflection\ReflectionHelper\CallStatic.cs:line 20
	   at Avarice.VfxEditorManager.RemoveVfx() in D:\VS\Avarice\Avarice\VfxEditorManager.cs:line 26
19:01:43.933 | WRN | "XIVSlothCombo" is accessing "ObjectTable" outside the main thread. This is deprecated.
19:01:59.708 | ERR | [Avarice] Object reference not set to an instance of an object.
19:01:59.708 | ERR | [Avarice]    at ECommons.Reflection.ReflectionHelper.CallStatic(Object obj, String type, String name, Object[] values) in D:\VS\Avarice\ECommons\ECommons\Reflection\ReflectionHelper\CallStatic.cs:line 20
	   at Avarice.VfxEditorManager.RemoveVfx() in D:\VS\Avarice\Avarice\VfxEditorManager.cs:line 26
19:02:14.001 | WRN | "XIVSlothCombo" is accessing "ObjectTable" outside the main thread. This is deprecated.
19:02:17.332 | ERR | [Avarice] Object reference not set to an instance of an object.
19:02:17.332 | ERR | [Avarice]    at ECommons.Reflection.ReflectionHelper.CallStatic(Object obj, String type, String name, Object[] values) in D:\VS\Avarice\ECommons\ECommons\Reflection\ReflectionHelper\CallStatic.cs:line 20
	   at Avarice.VfxEditorManager.RemoveVfx() in D:\VS\Avarice\Avarice\VfxEditorManager.cs:line 26
19:02:27.178 | ERR | [Avarice] Object reference not set to an instance of an object.
19:02:27.179 | ERR | [Avarice]    at ECommons.Reflection.ReflectionHelper.CallStatic(Object obj, String type, String name, Object[] values) in D:\VS\Avarice\ECommons\ECommons\Reflection\ReflectionHelper\CallStatic.cs:line 20
	   at Avarice.VfxEditorManager.RemoveVfx() in D:\VS\Avarice\Avarice\VfxEditorManager.cs:line 26
19:02:29.694 | ERR | [Avarice] Object reference not set to an instance of an object.
19:02:29.694 | ERR | [Avarice]    at ECommons.Reflection.ReflectionHelper.CallStatic(Object obj, String type, String name, Object[] values) in D:\VS\Avarice\ECommons\ECommons\Reflection\ReflectionHelper\CallStatic.cs:line 20
	   at Avarice.VfxEditorManager.RemoveVfx() in D:\VS\Avarice\Avarice\VfxEditorManager.cs:line 26
19:02:42.010 | ERR | [Avarice] Object reference not set to an instance of an object.
19:02:42.010 | ERR | [Avarice]    at ECommons.Reflection.ReflectionHelper.CallStatic(Object obj, String type, String name, Object[] values) in D:\VS\Avarice\ECommons\ECommons\Reflection\ReflectionHelper\CallStatic.cs:line 20
	   at Avarice.VfxEditorManager.RemoveVfx() in D:\VS\Avarice\Avarice\VfxEditorManager.cs:line 26
19:02:44.080 | WRN | "XIVSlothCombo" is accessing "ObjectTable" outside the main thread. This is deprecated.
19:02:54.770 | ERR | [Avarice] Object reference not set to an instance of an object.
19:02:54.770 | ERR | [Avarice]    at ECommons.Reflection.ReflectionHelper.CallStatic(Object obj, String type, String name, Object[] values) in D:\VS\Avarice\ECommons\ECommons\Reflection\ReflectionHelper\CallStatic.cs:line 20
	   at Avarice.VfxEditorManager.RemoveVfx() in D:\VS\Avarice\Avarice\VfxEditorManager.cs:line 26
19:02:59.651 | INF | [vnavmesh] Queueing move-to <-69.017, 322.988, -57.023>
19:02:59.694 | INF | [vnavmesh] Pathfinding complete
19:03:02.413 | INF | [vnavmesh] Queueing move-to <-69.444, 357.992, -91.997>
19:03:02.456 | INF | [vnavmesh] Pathfinding complete
19:03:14.248 | WRN | "XIVSlothCombo" is accessing "ObjectTable" outside the main thread. This is deprecated.
19:03:17.460 | ERR | [Avarice] Object reference not set to an instance of an object.
19:03:17.460 | ERR | [Avarice]    at ECommons.Reflection.ReflectionHelper.CallStatic(Object obj, String type, String name, Object[] values) in D:\VS\Avarice\ECommons\ECommons\Reflection\ReflectionHelper\CallStatic.cs:line 20
	   at Avarice.VfxEditorManager.RemoveVfx() in D:\VS\Avarice\Avarice\VfxEditorManager.cs:line 26
19:03:19.852 | ERR | [Avarice] Object reference not set to an instance of an object.
19:03:19.852 | ERR | [Avarice]    at ECommons.Reflection.ReflectionHelper.CallStatic(Object obj, String type, String name, Object[] values) in D:\VS\Avarice\ECommons\ECommons\Reflection\ReflectionHelper\CallStatic.cs:line 20
	   at Avarice.VfxEditorManager.RemoveVfx() in D:\VS\Avarice\Avarice\VfxEditorManager.cs:line 26
19:03:32.690 | ERR | [Avarice] Object reference not set to an instance of an object.
19:03:32.690 | ERR | [Avarice]    at ECommons.Reflection.ReflectionHelper.CallStatic(Object obj, String type, String name, Object[] values) in D:\VS\Avarice\ECommons\ECommons\Reflection\ReflectionHelper\CallStatic.cs:line 20
	   at Avarice.VfxEditorManager.RemoveVfx() in D:\VS\Avarice\Avarice\VfxEditorManager.cs:line 26
19:03:44.446 | WRN | "XIVSlothCombo" is accessing "ObjectTable" outside the main thread. This is deprecated.
19:03:44.981 | ERR | [Avarice] Object reference not set to an instance of an object.
19:03:44.981 | ERR | [Avarice]    at ECommons.Reflection.ReflectionHelper.CallStatic(Object obj, String type, String name, Object[] values) in D:\VS\Avarice\ECommons\ECommons\Reflection\ReflectionHelper\CallStatic.cs:line 20
	   at Avarice.VfxEditorManager.RemoveVfx() in D:\VS\Avarice\Avarice\VfxEditorManager.cs:line 26
19:03:57.407 | ERR | [Avarice] Object reference not set to an instance of an object.
19:03:57.407 | ERR | [Avarice]    at ECommons.Reflection.ReflectionHelper.CallStatic(Object obj, String type, String name, Object[] values) in D:\VS\Avarice\ECommons\ECommons\Reflection\ReflectionHelper\CallStatic.cs:line 20
	   at Avarice.VfxEditorManager.RemoveVfx() in D:\VS\Avarice\Avarice\VfxEditorManager.cs:line 26
19:03:59.920 | ERR | [Avarice] Object reference not set to an instance of an object.
19:03:59.920 | ERR | [Avarice]    at ECommons.Reflection.ReflectionHelper.CallStatic(Object obj, String type, String name, Object[] values) in D:\VS\Avarice\ECommons\ECommons\Reflection\ReflectionHelper\CallStatic.cs:line 20
	   at Avarice.VfxEditorManager.RemoveVfx() in D:\VS\Avarice\Avarice\VfxEditorManager.cs:line 26
19:04:12.152 | ERR | [Avarice] Object reference not set to an instance of an object.
19:04:12.152 | ERR | [Avarice]    at ECommons.Reflection.ReflectionHelper.CallStatic(Object obj, String type, String name, Object[] values) in D:\VS\Avarice\ECommons\ECommons\Reflection\ReflectionHelper\CallStatic.cs:line 20
	   at Avarice.VfxEditorManager.RemoveVfx() in D:\VS\Avarice\Avarice\VfxEditorManager.cs:line 26
19:04:17.691 | WRN | "XIVSlothCombo" is accessing "ObjectTable" outside the main thread. This is deprecated.
19:04:27.984 | ERR | [Avarice] Object reference not set to an instance of an object.
19:04:27.984 | ERR | [Avarice]    at ECommons.Reflection.ReflectionHelper.CallStatic(Object obj, String type, String name, Object[] values) in D:\VS\Avarice\ECommons\ECommons\Reflection\ReflectionHelper\CallStatic.cs:line 20
	   at Avarice.VfxEditorManager.RemoveVfx() in D:\VS\Avarice\Avarice\VfxEditorManager.cs:line 26
19:04:30.435 | ERR | [Avarice] Object reference not set to an instance of an object.
19:04:30.435 | ERR | [Avarice]    at ECommons.Reflection.ReflectionHelper.CallStatic(Object obj, String type, String name, Object[] values) in D:\VS\Avarice\ECommons\ECommons\Reflection\ReflectionHelper\CallStatic.cs:line 20
	   at Avarice.VfxEditorManager.RemoveVfx() in D:\VS\Avarice\Avarice\VfxEditorManager.cs:line 26
19:04:43.381 | ERR | [Avarice] Object reference not set to an instance of an object.
19:04:43.381 | ERR | [Avarice]    at ECommons.Reflection.ReflectionHelper.CallStatic(Object obj, String type, String name, Object[] values) in D:\VS\Avarice\ECommons\ECommons\Reflection\ReflectionHelper\CallStatic.cs:line 20
	   at Avarice.VfxEditorManager.RemoveVfx() in D:\VS\Avarice\Avarice\VfxEditorManager.cs:line 26
19:04:47.807 | WRN | "XIVSlothCombo" is accessing "ObjectTable" outside the main thread. This is deprecated.
19:04:55.685 | ERR | [Avarice] Object reference not set to an instance of an object.
19:04:55.685 | ERR | [Avarice]    at ECommons.Reflection.ReflectionHelper.CallStatic(Object obj, String type, String name, Object[] values) in D:\VS\Avarice\ECommons\ECommons\Reflection\ReflectionHelper\CallStatic.cs:line 20
	   at Avarice.VfxEditorManager.RemoveVfx() in D:\VS\Avarice\Avarice\VfxEditorManager.cs:line 26
19:05:17.586 | ERR | [Avarice] Object reference not set to an instance of an object.
19:05:17.586 | ERR | [Avarice]    at ECommons.Reflection.ReflectionHelper.CallStatic(Object obj, String type, String name, Object[] values) in D:\VS\Avarice\ECommons\ECommons\Reflection\ReflectionHelper\CallStatic.cs:line 20
	   at Avarice.VfxEditorManager.RemoveVfx() in D:\VS\Avarice\Avarice\VfxEditorManager.cs:line 26
19:05:19.362 | WRN | "XIVSlothCombo" is accessing "ObjectTable" outside the main thread. This is deprecated.
19:05:20.074 | ERR | [Avarice] Object reference not set to an instance of an object.
19:05:20.074 | ERR | [Avarice]    at ECommons.Reflection.ReflectionHelper.CallStatic(Object obj, String type, String name, Object[] values) in D:\VS\Avarice\ECommons\ECommons\Reflection\ReflectionHelper\CallStatic.cs:line 20
	   at Avarice.VfxEditorManager.RemoveVfx() in D:\VS\Avarice\Avarice\VfxEditorManager.cs:line 26
19:05:49.772 | WRN | "XIVSlothCombo" is accessing "ObjectTable" outside the main thread. This is deprecated.
19:05:55.289 | ERR | [Avarice] Object reference not set to an instance of an object.
19:05:55.289 | ERR | [Avarice]    at ECommons.Reflection.ReflectionHelper.CallStatic(Object obj, String type, String name, Object[] values) in D:\VS\Avarice\ECommons\ECommons\Reflection\ReflectionHelper\CallStatic.cs:line 20
	   at Avarice.VfxEditorManager.RemoveVfx() in D:\VS\Avarice\Avarice\VfxEditorManager.cs:line 26
19:06:10.015 | ERR | [Avarice] Object reference not set to an instance of an object.
19:06:10.015 | ERR | [Avarice]    at ECommons.Reflection.ReflectionHelper.CallStatic(Object obj, String type, String name, Object[] values) in D:\VS\Avarice\ECommons\ECommons\Reflection\ReflectionHelper\CallStatic.cs:line 20
	   at Avarice.VfxEditorManager.RemoveVfx() in D:\VS\Avarice\Avarice\VfxEditorManager.cs:line 26
19:06:20.005 | WRN | "XIVSlothCombo" is accessing "ObjectTable" outside the main thread. This is deprecated.
19:06:30.638 | INF | [SimpleTweaksPlugin] ItemID: 7569 Item Action: 0
19:06:30.639 | INF | [SimpleTweaksPlugin] ItemID: 7569 Item Action: 0
19:06:30.656 | ERR | [Avarice] Object reference not set to an instance of an object.
19:06:30.656 | ERR | [Avarice]    at ECommons.Reflection.ReflectionHelper.CallStatic(Object obj, String type, String name, Object[] values) in D:\VS\Avarice\ECommons\ECommons\Reflection\ReflectionHelper\CallStatic.cs:line 20
	   at Avarice.VfxEditorManager.RemoveVfx() in D:\VS\Avarice\Avarice\VfxEditorManager.cs:line 26
19:06:30.661 | INF | [SimpleTweaksPlugin] ItemID: 7569 Item Action: 0
19:06:33.060 | ERR | [Avarice] Object reference not set to an instance of an object.
19:06:33.060 | ERR | [Avarice]    at ECommons.Reflection.ReflectionHelper.CallStatic(Object obj, String type, String name, Object[] values) in D:\VS\Avarice\ECommons\ECommons\Reflection\ReflectionHelper\CallStatic.cs:line 20
	   at Avarice.VfxEditorManager.RemoveVfx() in D:\VS\Avarice\Avarice\VfxEditorManager.cs:line 26
19:06:46.254 | ERR | [Avarice] Object reference not set to an instance of an object.
19:06:46.254 | ERR | [Avarice]    at ECommons.Reflection.ReflectionHelper.CallStatic(Object obj, String type, String name, Object[] values) in D:\VS\Avarice\ECommons\ECommons\Reflection\ReflectionHelper\CallStatic.cs:line 20
	   at Avarice.VfxEditorManager.RemoveVfx() in D:\VS\Avarice\Avarice\VfxEditorManager.cs:line 26
19:06:50.506 | WRN | "XIVSlothCombo" is accessing "ObjectTable" outside the main thread. This is deprecated.
19:06:58.627 | ERR | [Avarice] Object reference not set to an instance of an object.
19:06:58.627 | ERR | [Avarice]    at ECommons.Reflection.ReflectionHelper.CallStatic(Object obj, String type, String name, Object[] values) in D:\VS\Avarice\ECommons\ECommons\Reflection\ReflectionHelper\CallStatic.cs:line 20
	   at Avarice.VfxEditorManager.RemoveVfx() in D:\VS\Avarice\Avarice\VfxEditorManager.cs:line 26
19:07:08.576 | ERR | [Avarice] Object reference not set to an instance of an object.
19:07:08.576 | ERR | [Avarice]    at ECommons.Reflection.ReflectionHelper.CallStatic(Object obj, String type, String name, Object[] values) in D:\VS\Avarice\ECommons\ECommons\Reflection\ReflectionHelper\CallStatic.cs:line 20
	   at Avarice.VfxEditorManager.RemoveVfx() in D:\VS\Avarice\Avarice\VfxEditorManager.cs:line 26
19:07:13.481 | ERR | [Avarice] Object reference not set to an instance of an object.
19:07:13.481 | ERR | [Avarice]    at ECommons.Reflection.ReflectionHelper.CallStatic(Object obj, String type, String name, Object[] values) in D:\VS\Avarice\ECommons\ECommons\Reflection\ReflectionHelper\CallStatic.cs:line 20
	   at Avarice.VfxEditorManager.RemoveVfx() in D:\VS\Avarice\Avarice\VfxEditorManager.cs:line 26
19:07:16.127 | INF | [vnavmesh] Queueing move-to <-69.570, 323.000, -56.890>
19:07:16.170 | INF | [vnavmesh] Pathfinding complete
19:07:26.494 | INF | [vnavmesh] Queueing move-to <-121.520, 328.080, -78.020>
19:07:26.537 | INF | [vnavmesh] Pathfinding complete
19:07:44.635 | INF | [vnavmesh] Queueing move-to <-153.230, 334.710, 0.860>
19:07:44.678 | INF | [vnavmesh] Pathfinding complete
19:08:01.385 | INF | [vnavmesh] Queueing move-to <-69.370, 358.070, -91.810>
19:08:01.428 | INF | [vnavmesh] Pathfinding complete
19:08:20.071 | WRN | "XIVSlothCombo" is accessing "ObjectTable" outside the main thread. This is deprecated.
19:08:23.029 | INF | [vnavmesh] Queueing move-to <-53.940, 376.010, -159.150>
19:08:23.072 | INF | [vnavmesh] Pathfinding complete
19:08:32.353 | INF | [vnavmesh] Queueing move-to <-53.980, 378.000, -197.580>
19:08:32.396 | INF | [vnavmesh] Pathfinding complete
19:08:34.266 | INF | [vnavmesh] Queueing move-to <-53.980, 378.000, -197.580>
19:08:34.309 | INF | [vnavmesh] Pathfinding complete
19:08:37.137 | INF | [AutoDuty] Starting Action Boss: Gurfurlur
19:08:37.181 | INF | [vnavmesh] Queueing move-to <-53.980, 378.000, -197.580>
19:08:37.224 | INF | [vnavmesh] Pathfinding complete
```

### Other relevant plugins installed

Rotation Solver Reborn 7.0.5.65
vnavmesh .0.0.0.41

**Comment by denoflionsx** [comment]
I can corroborate this report. Happens exactly as described.

It only resolves two ways:

1. The pack is killed. The character finishes walking to the chest, doubles back to the 2nd boss arena, then proceeds through the dungeon as if nothing went wrong.
2. The character dies/party wipes. The death and revival fixes it and everything proceeds as expected.

**Comment by RedactedFFXIV** [comment]
Can confirm, happens to me all the time too, specialy with mage dps

**Comment by Katsuvera** [comment]
Assuming this is the same issue I'm having, I figured out the issue:

The recent change to detect Treasure Coffers within 50yards (IIRC) when killing a boss means that, when you kill the second boss in Worqor Zormor, it loots the boss chest and ALSO detects the Coffer that's right before the third boss - because the Worqor Zormor Map actually loops around above the second boss' arena, so that 4th coffer is technically right beside the second boss arena. This screenshot below might help.

![image](https://github.com/user-attachments/assets/db4625a0-a1bb-450a-aec0-88b746f6b840)

**Comment by erdelf** [comment]
Thanks for the detective work @Katsuvera you were indeed correct.
fixed in 173 (aka next update) via https://github.com/ffxivcode/AutoDuty/commit/19ded6156044b933b040a9fc85e4368bcef45c05
