### ISSUE TITLE
[Bug] Random-ass crash

### ISSUE THREAD

**Issue by K0shachiyamyatA** [ffxivcode/AutoDuty#454]
### What happened?

clicked paths tab - game froze for a few seconds and then crashed without even dalamud crash log prompt and separate crash log

### Version Number

v0.0.0.165

### Steps to reproduce the error

click paths tab

### Relevant log output

```shell
2024-09-15 13:34:52.625 +04:00 [INF] [AutoDuty] C:\Users\user\AppData\Roaming\XIVLauncher\pluginConfigs\AutoDuty\paths\(1037) The Tam-Tara Deepcroft.json is not a valid duty path: System.FormatException: The input string '4.35' was not in a correct format.
   at System.Number.ThrowFormatException[TChar](ReadOnlySpan`1 value)
   at AutoDuty.Managers.ContentPathsManager.DutyPath.<>c__DisplayClass22_1.<get_PathFile>b__2(String x) in /home/runner/work/AutoDuty/AutoDuty/AutoDuty/Managers/ContentPathsManager.cs:line 213
   at AutoDuty.Managers.ContentPathsManager.DutyPath.get_PathFile() in /home/runner/work/AutoDuty/AutoDuty/AutoDuty/Managers/ContentPathsManager.cs:line 187
2024-09-15 13:34:52.626 +04:00 [INF] LASTEXCEPTION:eyJXaGVuIjoiMjAyNC0wOS0xNVQxMzozNDo1Mi42MjY2NzMrMDQ6MDAiLCJJbmZvIjoiU3lzdGVtLk51bGxSZWZlcmVuY2VFeGNlcHRpb246IE9iamVjdCByZWZlcmVuY2Ugbm90IHNldCB0byBhbiBpbnN0YW5jZSBvZiBhbiBvYmplY3QuXHJcbiAgIGF0IEF1dG9EdXR5LldpbmRvd3MuUGF0aHNUYWIuRHJhdygpIGluIC9ob21lL3J1bm5lci93b3JrL0F1dG9EdXR5L0F1dG9EdXR5L0F1dG9EdXR5L1dpbmRvd3MvUGF0aHNUYWIuY3M6bGluZSAxNTdcclxuICAgYXQgQXV0b0R1dHkuV2luZG93cy5NYWluV2luZG93LkV6VGFiQmFyKFN0cmluZyBpZCwgU3RyaW5nIEtvRmlUcmFuc3BhcmVudCwgU3RyaW5nIG9wZW5UYWJOYW1lLCBJbUd1aVRhYkJhckZsYWdzIGZsYWdzLCBWYWx1ZVR1cGxlYDRbXSB0YWJzKSBpbiAvaG9tZS9ydW5uZXIvd29yay9BdXRvRHV0eS9BdXRvRHV0eS9BdXRvRHV0eS9XaW5kb3dzL01haW5XaW5kb3cuY3M6bGluZSAzODlcclxuICAgYXQgQXV0b0R1dHkuV2luZG93cy5NYWluV2luZG93LkRyYXcoKSBpbiAvaG9tZS9ydW5uZXIvd29yay9BdXRvRHV0eS9BdXRvRHV0eS9BdXRvRHV0eS9XaW5kb3dzL01haW5XaW5kb3cuY3M6bGluZSA0MTFcclxuICAgYXQgRGFsYW11ZC5JbnRlcmZhY2UuV2luZG93aW5nLldpbmRvdy5EcmF3SW50ZXJuYWwoRGFsYW11ZENvbmZpZ3VyYXRpb24gY29uZmlndXJhdGlvbikgaW4gQzpcXGdvYXRzb2Z0XFxjb21wYW55c2VjcmV0c1xcZGFsYW11ZFxcXFxJbnRlcmZhY2VcXFdpbmRvd2luZ1xcV2luZG93LmNzOmxpbmUgMzQ2IiwiQ29udGV4dCI6IltXaW5kb3dTeXN0ZW1dIEVycm9yIGR1cmluZyBEcmF3KCk6IEF1dG9EdXR5IHYwLjAuMC4xNjUjIyNBdXRvZHV0eSJ9
2024-09-15 13:34:52.626 +04:00 [ERR] [WindowSystem] Error during Draw(): AutoDuty v0.0.0.165###Autoduty
System.NullReferenceException: Object reference not set to an instance of an object.
   at AutoDuty.Windows.PathsTab.Draw() in /home/runner/work/AutoDuty/AutoDuty/AutoDuty/Windows/PathsTab.cs:line 157
   at AutoDuty.Windows.MainWindow.EzTabBar(String id, String KoFiTransparent, String openTabName, ImGuiTabBarFlags flags, ValueTuple`4[] tabs) in /home/runner/work/AutoDuty/AutoDuty/AutoDuty/Windows/MainWindow.cs:line 389
   at AutoDuty.Windows.MainWindow.Draw() in /home/runner/work/AutoDuty/AutoDuty/AutoDuty/Windows/MainWindow.cs:line 411
   at Dalamud.Interface.Windowing.Window.DrawInternal(DalamudConfiguration configuration) in C:\goatsoft\companysecrets\dalamud\\Interface\Windowing\Window.cs:line 346
2024-09-15 13:34:52.648 +04:00 [INF] [AutoDuty] C:\Users\user\AppData\Roaming\XIVLauncher\pluginConfigs\AutoDuty\paths\(1037) The Tam-Tara Deepcroft.json is not a valid duty path: System.FormatException: The input string '4.35' was not in a correct format.
   at System.Number.ThrowFormatException[TChar](ReadOnlySpan`1 value)
   at AutoDuty.Managers.ContentPathsManager.DutyPath.<>c__DisplayClass22_1.<get_PathFile>b__2(String x) in /home/runner/work/AutoDuty/AutoDuty/AutoDuty/Managers/ContentPathsManager.cs:line 213
   at AutoDuty.Managers.ContentPathsManager.DutyPath.get_PathFile() in /home/runner/work/AutoDuty/AutoDuty/AutoDuty/Managers/ContentPathsManager.cs:line 187
2024-09-15 13:34:52.648 +04:00 [INF] LASTEXCEPTION:eyJXaGVuIjoiMjAyNC0wOS0xNVQxMzozNDo1Mi42NDg5NjE5KzA0OjAwIiwiSW5mbyI6IlN5c3RlbS5OdWxsUmVmZXJlbmNlRXhjZXB0aW9uOiBPYmplY3QgcmVmZXJlbmNlIG5vdCBzZXQgdG8gYW4gaW5zdGFuY2Ugb2YgYW4gb2JqZWN0LlxyXG4gICBhdCBBdXRvRHV0eS5XaW5kb3dzLlBhdGhzVGFiLkRyYXcoKSBpbiAvaG9tZS9ydW5uZXIvd29yay9BdXRvRHV0eS9BdXRvRHV0eS9BdXRvRHV0eS9XaW5kb3dzL1BhdGhzVGFiLmNzOmxpbmUgMTU3XHJcbiAgIGF0IEF1dG9EdXR5LldpbmRvd3MuTWFpbldpbmRvdy5FelRhYkJhcihTdHJpbmcgaWQsIFN0cmluZyBLb0ZpVHJhbnNwYXJlbnQsIFN0cmluZyBvcGVuVGFiTmFtZSwgSW1HdWlUYWJCYXJGbGFncyBmbGFncywgVmFsdWVUdXBsZWA0W10gdGFicykgaW4gL2hvbWUvcnVubmVyL3dvcmsvQXV0b0R1dHkvQXV0b0R1dHkvQXV0b0R1dHkvV2luZG93cy9NYWluV2luZG93LmNzOmxpbmUgMzg5XHJcbiAgIGF0IEF1dG9EdXR5LldpbmRvd3MuTWFpbldpbmRvdy5EcmF3KCkgaW4gL2hvbWUvcnVubmVyL3dvcmsvQXV0b0R1dHkvQXV0b0R1dHkvQXV0b0R1dHkvV2luZG93cy9NYWluV2luZG93LmNzOmxpbmUgNDExXHJcbiAgIGF0IERhbGFtdWQuSW50ZXJmYWNlLldpbmRvd2luZy5XaW5kb3cuRHJhd0ludGVybmFsKERhbGFtdWRDb25maWd1cmF0aW9uIGNvbmZpZ3VyYXRpb24pIGluIEM6XFxnb2F0c29mdFxcY29tcGFueXNlY3JldHNcXGRhbGFtdWRcXFxcSW50ZXJmYWNlXFxXaW5kb3dpbmdcXFdpbmRvdy5jczpsaW5lIDM0NiIsIkNvbnRleHQiOiJbV2luZG93U3lzdGVtXSBFcnJvciBkdXJpbmcgRHJhdygpOiBBdXRvRHV0eSB2MC4wLjAuMTY1IyMjQXV0b2R1dHkifQ==
2024-09-15 13:34:52.648 +04:00 [ERR] [WindowSystem] Error during Draw(): AutoDuty v0.0.0.165###Autoduty
System.NullReferenceException: Object reference not set to an instance of an object.
   at AutoDuty.Windows.PathsTab.Draw() in /home/runner/work/AutoDuty/AutoDuty/AutoDuty/Windows/PathsTab.cs:line 157
   at AutoDuty.Windows.MainWindow.EzTabBar(String id, String KoFiTransparent, String openTabName, ImGuiTabBarFlags flags, ValueTuple`4[] tabs) in /home/runner/work/AutoDuty/AutoDuty/AutoDuty/Windows/MainWindow.cs:line 389
   at AutoDuty.Windows.MainWindow.Draw() in /home/runner/work/AutoDuty/AutoDuty/AutoDuty/Windows/MainWindow.cs:line 411
   at Dalamud.Interface.Windowing.Window.DrawInternal(DalamudConfiguration configuration) in C:\goatsoft\companysecrets\dalamud\\Interface\Windowing\Window.cs:line 346
2024-09-15 13:34:52.664 +04:00 [INF] [AutoDuty] C:\Users\user\AppData\Roaming\XIVLauncher\pluginConfigs\AutoDuty\paths\(1039) The Thousand Maws of Toto-Rak.json is not a valid duty path: System.FormatException: The input string '-112.77' was not in a correct format.
   at System.Number.ThrowFormatException[TChar](ReadOnlySpan`1 value)
   at AutoDuty.Managers.ContentPathsManager.DutyPath.<>c__DisplayClass22_1.<get_PathFile>b__2(String x) in /home/runner/work/AutoDuty/AutoDuty/AutoDuty/Managers/ContentPathsManager.cs:line 213
   at AutoDuty.Managers.ContentPathsManager.DutyPath.get_PathFile() in /home/runner/work/AutoDuty/AutoDuty/AutoDuty/Managers/ContentPathsManager.cs:line 187
2024-09-15 13:34:52.664 +04:00 [INF] LASTEXCEPTION:eyJXaGVuIjoiMjAyNC0wOS0xNVQxMzozNDo1Mi42NjQyOTA1KzA0OjAwIiwiSW5mbyI6IlN5c3RlbS5Db2xsZWN0aW9ucy5HZW5lcmljLktleU5vdEZvdW5kRXhjZXB0aW9uOiBUaGUgZ2l2ZW4ga2V5ICcxMDM5JyB3YXMgbm90IHByZXNlbnQgaW4gdGhlIGRpY3Rpb25hcnkuXHJcbiAgIGF0IFN5c3RlbS5Db2xsZWN0aW9ucy5HZW5lcmljLkRpY3Rpb25hcnlgMi5nZXRfSXRlbShUS2V5IGtleSlcclxuICAgYXQgQXV0b0R1dHkuTWFuYWdlcnMuQ29udGVudFBhdGhzTWFuYWdlci5EdXR5UGF0aC5nZXRfUGF0aEZpbGUoKSBpbiAvaG9tZS9ydW5uZXIvd29yay9BdXRvRHV0eS9BdXRvRHV0eS9BdXRvRHV0eS9NYW5hZ2Vycy9Db250ZW50UGF0aHNNYW5hZ2VyLmNzOmxpbmUgMzI5XHJcbiAgIGF0IEF1dG9EdXR5LldpbmRvd3MuUGF0aHNUYWIuRHJhdygpIGluIC9ob21lL3J1bm5lci93b3JrL0F1dG9EdXR5L0F1dG9EdXR5L0F1dG9EdXR5L1dpbmRvd3MvUGF0aHNUYWIuY3M6bGluZSAxNTdcclxuICAgYXQgQXV0b0R1dHkuV2luZG93cy5NYWluV2luZG93LkV6VGFiQmFyKFN0cmluZyBpZCwgU3RyaW5nIEtvRmlUcmFuc3BhcmVudCwgU3RyaW5nIG9wZW5UYWJOYW1lLCBJbUd1aVRhYkJhckZsYWdzIGZsYWdzLCBWYWx1ZVR1cGxlYDRbXSB0YWJzKSBpbiAvaG9tZS9ydW5uZXIvd29yay9BdXRvRHV0eS9BdXRvRHV0eS9BdXRvRHV0eS9XaW5kb3dzL01haW5XaW5kb3cuY3M6bGluZSAzODlcclxuICAgYXQgQXV0b0R1dHkuV2luZG93cy5NYWluV2luZG93LkRyYXcoKSBpbiAvaG9tZS9ydW5uZXIvd29yay9BdXRvRHV0eS9BdXRvRHV0eS9BdXRvRHV0eS9XaW5kb3dzL01haW5XaW5kb3cuY3M6bGluZSA0MTFcclxuICAgYXQgRGFsYW11ZC5JbnRlcmZhY2UuV2luZG93aW5nLldpbmRvdy5EcmF3SW50ZXJuYWwoRGFsYW11ZENvbmZpZ3VyYXRpb24gY29uZmlndXJhdGlvbikgaW4gQzpcXGdvYXRzb2Z0XFxjb21wYW55c2VjcmV0c1xcZGFsYW11ZFxcXFxJbnRlcmZhY2VcXFdpbmRvd2luZ1xcV2luZG93LmNzOmxpbmUgMzQ2IiwiQ29udGV4dCI6IltXaW5kb3dTeXN0ZW1dIEVycm9yIGR1cmluZyBEcmF3KCk6IEF1dG9EdXR5IHYwLjAuMC4xNjUjIyNBdXRvZHV0eSJ9
2024-09-15 13:34:52.664 +04:00 [ERR] [WindowSystem] Error during Draw(): AutoDuty v0.0.0.165###Autoduty
System.Collections.Generic.KeyNotFoundException: The given key '1039' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at AutoDuty.Managers.ContentPathsManager.DutyPath.get_PathFile() in /home/runner/work/AutoDuty/AutoDuty/AutoDuty/Managers/ContentPathsManager.cs:line 329
   at AutoDuty.Windows.PathsTab.Draw() in /home/runner/work/AutoDuty/AutoDuty/AutoDuty/Windows/PathsTab.cs:line 157
   at AutoDuty.Windows.MainWindow.EzTabBar(String id, String KoFiTransparent, String openTabName, ImGuiTabBarFlags flags, ValueTuple`4[] tabs) in /home/runner/work/AutoDuty/AutoDuty/AutoDuty/Windows/MainWindow.cs:line 389
   at AutoDuty.Windows.MainWindow.Draw() in /home/runner/work/AutoDuty/AutoDuty/AutoDuty/Windows/MainWindow.cs:line 411
   at Dalamud.Interface.Windowing.Window.DrawInternal(DalamudConfiguration configuration) in C:\goatsoft\companysecrets\dalamud\\Interface\Windowing\Window.cs:line 346
2024-09-15 13:34:52.674 +04:00 [INF] [AutoDuty] C:\Users\user\AppData\Roaming\XIVLauncher\pluginConfigs\AutoDuty\paths\(1037) The Tam-Tara Deepcroft.json is not a valid duty path: System.FormatException: The input string '4.35' was not in a correct format.
   at System.Number.ThrowFormatException[TChar](ReadOnlySpan`1 value)
   at AutoDuty.Managers.ContentPathsManager.DutyPath.<>c__DisplayClass22_1.<get_PathFile>b__2(String x) in /home/runner/work/AutoDuty/AutoDuty/AutoDuty/Managers/ContentPathsManager.cs:line 213
   at AutoDuty.Managers.ContentPathsManager.DutyPath.get_PathFile() in /home/runner/work/AutoDuty/AutoDuty/AutoDuty/Managers/ContentPathsManager.cs:line 187
2024-09-15 13:34:52.674 +04:00 [INF] LASTEXCEPTION:eyJXaGVuIjoiMjAyNC0wOS0xNVQxMzozNDo1Mi42NzQ4NDMzKzA0OjAwIiwiSW5mbyI6IlN5c3RlbS5OdWxsUmVmZXJlbmNlRXhjZXB0aW9uOiBPYmplY3QgcmVmZXJlbmNlIG5vdCBzZXQgdG8gYW4gaW5zdGFuY2Ugb2YgYW4gb2JqZWN0LlxyXG4gICBhdCBBdXRvRHV0eS5XaW5kb3dzLlBhdGhzVGFiLkRyYXcoKSBpbiAvaG9tZS9ydW5uZXIvd29yay9BdXRvRHV0eS9BdXRvRHV0eS9BdXRvRHV0eS9XaW5kb3dzL1BhdGhzVGFiLmNzOmxpbmUgMTU3XHJcbiAgIGF0IEF1dG9EdXR5LldpbmRvd3MuTWFpbldpbmRvdy5FelRhYkJhcihTdHJpbmcgaWQsIFN0cmluZyBLb0ZpVHJhbnNwYXJlbnQsIFN0cmluZyBvcGVuVGFiTmFtZSwgSW1HdWlUYWJCYXJGbGFncyBmbGFncywgVmFsdWVUdXBsZWA0W10gdGFicykgaW4gL2hvbWUvcnVubmVyL3dvcmsvQXV0b0R1dHkvQXV0b0R1dHkvQXV0b0R1dHkvV2luZG93cy9NYWluV2luZG93LmNzOmxpbmUgMzg5XHJcbiAgIGF0IEF1dG9EdXR5LldpbmRvd3MuTWFpbldpbmRvdy5EcmF3KCkgaW4gL2hvbWUvcnVubmVyL3dvcmsvQXV0b0R1dHkvQXV0b0R1dHkvQXV0b0R1dHkvV2luZG93cy9NYWluV2luZG93LmNzOmxpbmUgNDExXHJcbiAgIGF0IERhbGFtdWQuSW50ZXJmYWNlLldpbmRvd2luZy5XaW5kb3cuRHJhd0ludGVybmFsKERhbGFtdWRDb25maWd1cmF0aW9uIGNvbmZpZ3VyYXRpb24pIGluIEM6XFxnb2F0c29mdFxcY29tcGFueXNlY3JldHNcXGRhbGFtdWRcXFxcSW50ZXJmYWNlXFxXaW5kb3dpbmdcXFdpbmRvdy5jczpsaW5lIDM0NiIsIkNvbnRleHQiOiJbV2luZG93U3lzdGVtXSBFcnJvciBkdXJpbmcgRHJhdygpOiBBdXRvRHV0eSB2MC4wLjAuMTY1IyMjQXV0b2R1dHkifQ==
2024-09-15 13:34:52.674 +04:00 [ERR] [WindowSystem] Error during Draw(): AutoDuty v0.0.0.165###Autoduty
System.NullReferenceException: Object reference not set to an instance of an object.
   at AutoDuty.Windows.PathsTab.Draw() in /home/runner/work/AutoDuty/AutoDuty/AutoDuty/Windows/PathsTab.cs:line 157
   at AutoDuty.Windows.MainWindow.EzTabBar(String id, String KoFiTransparent, String openTabName, ImGuiTabBarFlags flags, ValueTuple`4[] tabs) in /home/runner/work/AutoDuty/AutoDuty/AutoDuty/Windows/MainWindow.cs:line 389
   at AutoDuty.Windows.MainWindow.Draw() in /home/runner/work/AutoDuty/AutoDuty/AutoDuty/Windows/MainWindow.cs:line 411
   at Dalamud.Interface.Windowing.Window.DrawInternal(DalamudConfiguration configuration) in C:\goatsoft\companysecrets\dalamud\\Interface\Windowing\Window.cs:line 346
2024-09-15 13:34:52.693 +04:00 [INF] [AutoDuty] C:\Users\user\AppData\Roaming\XIVLauncher\pluginConfigs\AutoDuty\paths\(1039) The Thousand Maws of Toto-Rak.json is not a valid duty path: System.FormatException: The input string '-112.77' was not in a correct format.
   at System.Number.ThrowFormatException[TChar](ReadOnlySpan`1 value)
   at AutoDuty.Managers.ContentPathsManager.DutyPath.<>c__DisplayClass22_1.<get_PathFile>b__2(String x) in /home/runner/work/AutoDuty/AutoDuty/AutoDuty/Managers/ContentPathsManager.cs:line 213
   at AutoDuty.Managers.ContentPathsManager.DutyPath.get_PathFile() in /home/runner/work/AutoDuty/AutoDuty/AutoDuty/Managers/ContentPathsManager.cs:line 187
2024-09-15 13:34:52.694 +04:00 [INF] LASTEXCEPTION:eyJXaGVuIjoiMjAyNC0wOS0xNVQxMzozNDo1Mi42OTQxMTU4KzA0OjAwIiwiSW5mbyI6IlN5c3RlbS5OdWxsUmVmZXJlbmNlRXhjZXB0aW9uOiBPYmplY3QgcmVmZXJlbmNlIG5vdCBzZXQgdG8gYW4gaW5zdGFuY2Ugb2YgYW4gb2JqZWN0LlxyXG4gICBhdCBBdXRvRHV0eS5XaW5kb3dzLlBhdGhzVGFiLkRyYXcoKSBpbiAvaG9tZS9ydW5uZXIvd29yay9BdXRvRHV0eS9BdXRvRHV0eS9BdXRvRHV0eS9XaW5kb3dzL1BhdGhzVGFiLmNzOmxpbmUgMTU3XHJcbiAgIGF0IEF1dG9EdXR5LldpbmRvd3MuTWFpbldpbmRvdy5FelRhYkJhcihTdHJpbmcgaWQsIFN0cmluZyBLb0ZpVHJhbnNwYXJlbnQsIFN0cmluZyBvcGVuVGFiTmFtZSwgSW1HdWlUYWJCYXJGbGFncyBmbGFncywgVmFsdWVUdXBsZWA0W10gdGFicykgaW4gL2hvbWUvcnVubmVyL3dvcmsvQXV0b0R1dHkvQXV0b0R1dHkvQXV0b0R1dHkvV2luZG93cy9NYWluV2luZG93LmNzOmxpbmUgMzg5XHJcbiAgIGF0IEF1dG9EdXR5LldpbmRvd3MuTWFpbldpbmRvdy5EcmF3KCkgaW4gL2hvbWUvcnVubmVyL3dvcmsvQXV0b0R1dHkvQXV0b0R1dHkvQXV0b0R1dHkvV2luZG93cy9NYWluV2luZG93LmNzOmxpbmUgNDExXHJcbiAgIGF0IERhbGFtdWQuSW50ZXJmYWNlLldpbmRvd2luZy5XaW5kb3cuRHJhd0ludGVybmFsKERhbGFtdWRDb25maWd1cmF0aW9uIGNvbmZpZ3VyYXRpb24pIGluIEM6XFxnb2F0c29mdFxcY29tcGFueXNlY3JldHNcXGRhbGFtdWRcXFxcSW50ZXJmYWNlXFxXaW5kb3dpbmdcXFdpbmRvdy5jczpsaW5lIDM0NiIsIkNvbnRleHQiOiJbV2luZG93U3lzdGVtXSBFcnJvciBkdXJpbmcgRHJhdygpOiBBdXRvRHV0eSB2MC4wLjAuMTY1IyMjQXV0b2R1dHkifQ==
2024-09-15 13:34:52.694 +04:00 [ERR] [WindowSystem] Error during Draw(): AutoDuty v0.0.0.165###Autoduty
System.NullReferenceException: Object reference not set to an instance of an object.
   at AutoDuty.Windows.PathsTab.Draw() in /home/runner/work/AutoDuty/AutoDuty/AutoDuty/Windows/PathsTab.cs:line 157
   at AutoDuty.Windows.MainWindow.EzTabBar(String id, String KoFiTransparent, String openTabName, ImGuiTabBarFlags flags, ValueTuple`4[] tabs) in /home/runner/work/AutoDuty/AutoDuty/AutoDuty/Windows/MainWindow.cs:line 389
   at AutoDuty.Windows.MainWindow.Draw() in /home/runner/work/AutoDuty/AutoDuty/AutoDuty/Windows/MainWindow.cs:line 411
   at Dalamud.Interface.Windowing.Window.DrawInternal(DalamudConfiguration configuration) in C:\goatsoft\companysecrets\dalamud\\Interface\Windowing\Window.cs:line 346
```

**Comment by ThisIsNoTa2acc** [comment]
> Are those 2 path files modified? Can you upload them here

I didn't edit anything, maybe it's some bug with update

**Comment by Herculezz55** [comment]
OK, can you upload those 2 files please

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by K0shachiyamyatA** [comment]
> Are those 2 path files modified? Can you upload them here

no they aren't, ok

[(1037) The Tam-Tara Deepcroft.json](https://github.com/user-attachments/files/17015994/1037.The.Tam-Tara.Deepcroft.json)
[(1039) The Thousand Maws of Toto-Rak.json](https://github.com/user-attachments/files/17015997/1039.The.Thousand.Maws.of.Toto-Rak.json)

**Comment by Herculezz55** [comment]
Ty I will investigate in the mean time replace all your paths with the ones on here

**Comment by K0shachiyamyatA** [comment]
> Ty I will investigate in the mean time replace all your paths with the ones on here

replaced paths with those from the repo just now, still crashes

**Comment by Herculezz55** [comment]
please reopen those files after you replaced them and show me the very bottom as a screenshot, also new log as well pls

**Comment by Herculezz55** [comment]
ok those are not the files on github, delete your entire paths folder then reinstall autoduty

**Comment by K0shachiyamyatA** [comment]
> ok those are not the files on github, delete your entire paths folder then reinstall autoduty

well then it is some bad update, fixed.
