### ISSUE TITLE
[Bug] Index error with MoveTo steps

### ISSUE THREAD

**Issue by Tiroth** [ffxivcode/AutoDuty#481]
### What happened?

I created a path for Pharos Sirius, then ran the path. The plugin threw an error at the first MoveTo step and every MoveTo after. This also occurred with every other dungeon I tried to make a path for. 
![image](https://github.com/user-attachments/assets/5c413ebf-39ed-4eb6-aa1a-c954d9b08a49)

I went to the Build tab, selected the step, and clicked Modify without actually changing anything. This resolved the error.

### Version Number

169

### Steps to reproduce the error

1. Create path with 1+ MoveTo steps
2. Run path

### Relevant log output

```shell
17:29:01.437 | ERR | Exception during raise of "Void <InvokeSafely>b__0()"
	System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
	   at System.Collections.Generic.List`1.get_Item(Int32 index)
	   at AutoDuty.AutoDuty.StageReadingPath() in /home/runner/work/AutoDuty/AutoDuty/AutoDuty/AutoDuty.cs:line 882
	   at Dalamud.Utility.EventHandlerExtensions.HandleInvoke(Action act) in C:\goatsoft\companysecrets\dalamud\\Utility\EventHandlerExtensions.cs:line 124
```

### Other relevant plugins installed

17:37:18.061 | INF | [DUI] Penumbra
17:37:18.061 | INF | [DUI] Palace Pal
17:37:18.061 | INF | [DUI] Neko Fans NSFW 18+ Patch
17:37:18.061 | INF | [DUI] Neko Fans
17:37:18.061 | INF | [DUI] NecroLens
17:37:18.061 | INF | [DUI] ezMiniCactpot
17:37:18.061 | INF | [DUI] Saucy
17:37:18.061 | INF | [DUI] SkipCutscene
17:37:18.061 | INF | [DUI] XIVSlothCombo
17:37:18.061 | INF | [DUI] Easier Faux Hollows
17:37:18.061 | INF | [DUI] Slice is Right
17:37:18.061 | INF | [DUI] Lemegeton
17:37:18.061 | INF | [DUI] Congratulations
17:37:18.061 | INF | [DUI] Collections
17:37:18.061 | INF | [DUI] Boss Mod
17:37:18.061 | INF | [DUI] Fancy Loading Screens
17:37:18.061 | INF | [DUI] Character Data Sync
17:37:18.061 | INF | [DUI] Fungah
17:37:18.061 | INF | [DUI] MonsterDex
17:37:18.061 | INF | [DUI] Marketbuddy
17:37:18.061 | INF | [DUI] ezWondrousTails
17:37:18.061 | INF | [DUI] Workshoppa
17:37:18.061 | INF | [DUI] Pixel Perfect
17:37:18.061 | INF | [DUI] Burning Down the House
17:37:18.061 | INF | [DUI] Globetrotter
17:37:18.061 | INF | [DUI] Squadronista
17:37:18.061 | INF | [DUI] BigPlayerDebuffs
17:37:18.061 | INF | [DUI] Where's my mouse
17:37:18.061 | INF | [DUI] ChatCoordinates
17:37:18.061 | INF | [DUI] TriadBuddy
17:37:18.061 | INF | [DUI] Peeping Tom
17:37:18.061 | INF | [DUI] PingPlugin
17:37:18.061 | INF | [DUI] Aetherment
17:37:18.061 | INF | [DUI] Visibility
17:37:18.061 | INF | [DUI] FPS Plugin
17:37:18.061 | INF | [DUI] Teleporter
17:37:18.061 | INF | [DUI] Hunt Buddy
17:37:18.061 | INF | [DUI] Character Panel Refined
17:37:18.061 | INF | [DUI] Item Search
17:37:18.061 | INF | [DUI] JustBackup
17:37:18.061 | INF | [DUI] Simple Tweaks Plugin
17:37:18.061 | INF | [DUI] AntiAfkKick
17:37:18.061 | INF | [DUI] Ready Check Helper
17:37:18.061 | INF | [DUI] Glamaholic
17:37:18.061 | INF | [DUI] ZodiacBuddy
17:37:18.061 | INF | [DUI] LazyLoot
17:37:18.061 | INF | [DUI] Inventory Search Bar
17:37:18.061 | INF | [DUI] NoSoliciting
17:37:18.061 | INF | [DUI] Deliveroo
17:37:18.061 | INF | [DUI] TextAdvance
17:37:18.061 | INF | [DUI] Distance
17:37:18.061 | INF | [DUI] Waymark Preset Plugin
17:37:18.061 | INF | [DUI] Battlevest
17:37:18.061 | INF | [DUI] Umbra XIV
17:37:18.061 | INF | [DUI] AutoRetainer
17:37:18.061 | INF | [DUI] ARC
17:37:18.061 | INF | [DUI] Divination.FaloopIntegration
17:37:18.061 | INF | [DUI] Divination.AetheryteLinkInChat
17:37:18.061 | INF | [DUI] HaselTweaks
17:37:18.061 | INF | [DUI] V(ery) Island
17:37:18.061 | INF | [DUI] CurrencyAlert
17:37:18.061 | INF | [DUI] Expanded Search Info
17:37:18.061 | INF | [DUI] Sonar
17:37:18.061 | INF | [DUI] Market board
17:37:18.061 | INF | [DUI] QoL Bar
17:37:18.061 | INF | [DUI] Price Insight
17:37:18.061 | INF | [DUI] vnavmesh
17:37:18.061 | INF | [DUI] EngageTimer
17:37:18.061 | INF | [DUI] Something Need Doing (Expanded Edition)
17:37:18.061 | INF | [DUI] AutoHook
17:37:18.061 | INF | [DUI] Penny Pincher
17:37:18.061 | INF | [DUI] Chat Bubbles
17:37:18.061 | INF | [DUI] Death Recap
17:37:18.061 | INF | [DUI] Automaton
17:37:18.061 | INF | [DUI] Submarine Tracker
17:37:18.061 | INF | [DUI] DailyDuty
17:37:18.061 | INF | [DUI] Artisan
17:37:18.061 | INF | [DUI] Questionable
17:37:18.061 | INF | [DUI] AutoDuty
17:37:18.061 | INF | [DUI] Item Vendor Location
17:37:18.061 | INF | [DUI] Cammy
17:37:18.061 | INF | [DUI] Pandora's Box
17:37:18.061 | INF | [DUI] Accountant
17:37:18.061 | INF | [DUI] GatherBuddy Reborn
17:37:18.061 | INF | [DUI] ReAction
17:37:18.061 | INF | [DUI] VFXEditor
17:37:18.061 | INF | [DUI] JobBars
17:37:18.061 | INF | [DUI] Allagan Tools
17:37:18.061 | INF | [DUI] Lifestream
17:37:18.061 | INF | [DUI] HuntTrainAssistant
17:37:18.061 | INF | [DUI] Rotation Solver Reborn
17:37:18.061 | INF | [DUI] Yes Already
17:37:18.061 | INF | [DUI] BossMod Reborn
17:37:18.061 | INF | [DUI] Splatoon

### Plugin config file

{
  "$type": "AutoDuty.Windows.Configuration, AutoDuty",
  "DoNotUpdatePathFiles": [
    "(693) Deltascape V3.0.json"
  ],
  "PathSelections": {
    "$type": "System.Collections.Generic.Dictionary`2[[System.UInt32, System.Private.CoreLib],[System.Collections.Generic.Dictionary`2[[ECommons.ExcelServices.Job, ECommons],[System.Int32, System.Private.CoreLib]], System.Private.CoreLib]], System.Private.CoreLib"
  },
  "AutoScroll": true,
  "LogEventLevel": 0,
  "LoopTimes": 1,
  "Unsynced": true,
  "HideUnavailableDuties": true,
  "ShowMainWindowOnStartup": false,
  "ShowDutyLoopText": true,
  "ShowActionText": true,
  "UseSliderInputs": false,
  "OverrideOverlayButtons": true,
  "GotoButton": true,
  "TurninButton": true,
  "DesynthButton": true,
  "ExtractButton": true,
  "RepairButton": true,
  "EquipButton": true,
  "AutoExitDuty": true,
  "AutoManageRotationPluginState": true,
  "AutoManageVnavAlignCamera": true,
  "LootTreasure": true,
  "LootMethodEnum": 0,
  "LootBossTreasureOnly": false,
  "TreasureCofferScanDistance": 15,
  "OverridePartyValidation": false,
  "UsingAlternativeRotationPlugin": false,
  "UsingAlternativeMovementPlugin": false,
  "UsingAlternativeBossPlugin": false,
  "EnablePreLoopActions": false,
  "ExecuteCommandsPreLoop": false,
  "CustomCommandsPreLoop": [],
  "RetireMode": true,
  "RetireLocationEnum": 0,
  "PersonalHomeEntrancePath": [],
  "FCEstateEntrancePath": [],
  "AutoEquipRecommendedGear": false,
  "AutoEquipRecommendedGearGearsetter": false,
  "AutoRepair": true,
  "AutoRepairPct": 50,
  "AutoRepairSelf": true,
  "PreferredRepairNPC": null,
  "AutoConsume": false,
  "AutoConsumeIgnoreStatus": false,
  "AutoConsumeItemsList": [],
  "EnableBetweenLoopActions": false,
  "WaitTimeBeforeAfterLoopActions": 0,
  "AutoExtract": false,
  "AutoGCTurninSlotsLeft": 25,
  "AutoGCTurninSlotsLeftBool": false,
  "AutoGCTurninUseTicket": false,
  "EnableAutoRetainer": true,
  "PreferredSummoningBellEnum": 0,
  "AM": false,
  "UnhideAM": false,
  "EnableTerminationActions": false,
  "StopLevel": false,
  "StopLevelInt": 100,
  "StopNoRestedXP": false,
  "StopItemQty": false,
  "StopItemQtyItemDictionary": {
    "$type": "System.Collections.Generic.Dictionary`2[[System.UInt32, System.Private.CoreLib],[System.Collections.Generic.KeyValuePair`2[[System.String, System.Private.CoreLib],[System.Int32, System.Private.CoreLib]], System.Private.CoreLib]], System.Private.CoreLib",
    "35982": {
      "Key": "Tiny Troll",
      "Value": 1
    }
  },
  "StopItemQtyInt": 1,
  "ExecuteCommandsTermination": false,
  "CustomCommandsTermination": [],
  "PlayEndSound": false,
  "CustomSound": false,
  "CustomSoundVolume": 0.5,
  "SoundEnum": 0,
  "SoundPath": "",
  "TerminationMethodEnum": 2,
  "TerminationKeepActive": true,
  "HideBossModAIConfig": false,
  "FollowDuringCombat": true,
  "FollowDuringActiveBossModule": true,
  "FollowOutOfCombat": false,
  "FollowTarget": true,
  "FollowSlotInt": 1,
  "FollowRoleEnum": 1,
  "MaxDistanceToTargetFloat": 10.0,
  "MaxDistanceToTargetAoEFloat": 10.0,
  "MaxDistanceToSlotFloat": 1.0,
  "PositionalEnum": 0,
  "SelectedTrustMembers": [
    5,
    6,
    2
  ],
  "Version": 169,
  "DutyModeEnum": 8,
  "ShowOverlay": false,
  "HideOverlayWhenStopped": true,
  "LockOverlay": false,
  "OverlayNoBG": false,
  "AutoManageBossModAISettings": true,
  "AutoExtractAll": false,
  "AutoDesynth": false,
  "AutoDesynthSkillUp": false,
  "AutoGCTurnin": false,
  "FollowSelf": true,
  "FollowSlot": false,
  "FollowRole": false,
  "MaxDistanceToTargetRoleBased": true,
  "PositionalRoleBased": true
}

**Comment by Tiroth** [comment]
![image](https://github.com/user-attachments/assets/1e09e1f8-2d47-4036-935d-cd41abec0419)
![image](https://github.com/user-attachments/assets/b26580a2-dd84-43c2-bb28-bef76cd8c488)
