### ISSUE TITLE
[Bug] Adding "special interactable" to a path (qarn hard) causes exception

### ISSUE THREAD

**Issue by Tiroth** [ffxivcode/AutoDuty#493]
### What happened?

tried to run Qarn (Hard) and all interactables are missing object ids and do not work.
tried to add the first object as a special interactable caused an exception:

```
17:17:17.119 | ERR | Exception during raise of "Void <InvokeSafely>b__0()"
    System.FormatException: The input string '' was not in a correct format.
       at System.Number.ThrowFormatException[TChar](ReadOnlySpan`1 value)
       at AutoDuty.AutoDuty.<InteractablesCheck>b__125_2(ValueTuple`2 x) in /home/runner/work/AutoDuty/AutoDuty/AutoDuty/AutoDuty.cs:line 1348
       at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
       at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Boolean& found)
       at AutoDuty.AutoDuty.InteractablesCheck() in /home/runner/work/AutoDuty/AutoDuty/AutoDuty/AutoDuty.cs:line 1348
       at AutoDuty.AutoDuty.PreStageChecks() in /home/runner/work/AutoDuty/AutoDuty/AutoDuty/AutoDuty.cs:line 1364
       at AutoDuty.AutoDuty.Framework_Update(IFramework framework) in /home/runner/work/AutoDuty/AutoDuty/AutoDuty/AutoDuty.cs:line 1393
       at Dalamud.Utility.EventHandlerExtensions.HandleInvoke(Action act) in C:\goatsoft\companysecrets\dalamud\\Utility\EventHandlerExtensions.cs:line 124
```

### Version Number

170

### Steps to reproduce the error

try to add a special interactable to the sunken temple of qarn (hard) path

side note: the special interactable wasn't even necessary. just needed to put the object ids in the interactable steps.

**Comment by ggscott** [comment]
Can confirm interactibles via Squad missions (Pharos Serious [Hard]) aren't working as well.  Just in case its around the same bug - I don't know if its objectID based as I haven't dug too deep yet.  Just wanted to note whilst I try to debug

**Comment by Herculezz55** [comment]
Interactables was a experimental feature that has since been removed. A new more automated implementation is planned
