### ISSUE TITLE
[Bug] Trust leveling softlock

### ISSUE THREAD

**Issue by K0shachiyamyatA** [ffxivcode/AutoDuty#609]
### What happened?

when transitioning from The Qitana Ravel to The Tower of Zot as a dps, fails to pick up new party members
(i think Ryne is to blame)
![ffxiv_dx11_wZo52Y9Zjd](https://github.com/user-attachments/assets/be1a4065-84d8-4d4a-8412-e0a81d608250)

### Version Number

v0.0.0.172

### Steps to reproduce the error

when transitioning from The Qitana Ravel to The Tower of Zot as a dps, fails to pick up new party members
(i think Ryne is to blame)
![ffxiv_dx11_wZo52Y9Zjd](https://github.com/user-attachments/assets/be1a4065-84d8-4d4a-8412-e0a81d608250)

**Comment by erdelf** [comment]
the log part of the issue template wasn't for fun you know. Without a log I can't do much.

**Comment by K0shachiyamyatA** [comment]
> the log part of the issue template wasn't for fun you know. Without a log I can't do much.

```
2024-10-13 12:12:02.919 +04:00 [INF] [vnavmesh] Pathfinding complete
2024-10-13 12:12:04.643 +04:00 [INF] [vnavmesh] Queueing move-to <17,050  -77,000  -537,730>
2024-10-13 12:12:04.662 +04:00 [INF] [vnavmesh] Pathfinding complete
2024-10-13 12:12:07.211 +04:00 [INF] [AutoDuty] Starting Action Boss: null
2024-10-13 12:16:18.690 +04:00 [INF] [AutoDuty] ExitDuty Started
2024-10-13 12:16:21.904 +04:00 [INF] [vnavmesh] Starting transition from 'ex3/01_nvt_n4/dun/n4d3/level/n4d3//308D3//0.0.0.0' to ''
2024-10-13 12:16:22.682 +04:00 [INF] [vnavmesh] Starting transition from '' to 'ffxiv/sea_s1/twn/s1t2/level/s1t2//11F3A//18.19.0.0'
2024-10-13 12:16:22.720 +04:00 [INF] [vnavmesh] Finishing transition to 'ffxiv/sea_s1/twn/s1t2/level/s1t2//11F3A//18.19.0.0'
2024-10-13 12:16:24.061 +04:00 [INF] [AutoDuty] Leveling Trust Members set
2024-10-13 12:16:24.061 +04:00 [INF] [AutoDuty] 7
2024-10-13 12:16:24.061 +04:00 [INF] [AutoDuty] checking: Urianger
2024-10-13 12:16:24.061 +04:00 [INF] [AutoDuty] check successful
2024-10-13 12:16:24.061 +04:00 [INF] [AutoDuty] checking: Alphinaud
2024-10-13 12:16:24.061 +04:00 [INF] [AutoDuty] checking: Estinien
2024-10-13 12:16:24.061 +04:00 [INF] [AutoDuty] check successful
2024-10-13 12:16:24.061 +04:00 [INF] [AutoDuty] checking: Alisaie
2024-10-13 12:16:24.061 +04:00 [INF] [AutoDuty] checking: Thancred
2024-10-13 12:16:24.061 +04:00 [INF] [AutoDuty] check successful
2024-10-13 12:16:24.088 +04:00 [INF] [AutoDuty] ExitDuty Finished
2024-10-13 12:16:24.145 +04:00 [WRN] PlayerTrack is accessing ObjectTable outside the main thread. This is deprecated.
2024-10-13 12:16:24.307 +04:00 [INF] [AutoDuty] TrustHelper - Getting trust levels for expansion 3 from Holminster Switch
2024-10-13 12:16:24.307 +04:00 [INF] [AutoDuty] Get Trust Levels: Level not set for: Alphinaud | Urianger
2024-10-13 12:16:24.905 +04:00 [INF] [AutoDuty] TrustHelper - Done getting trust levels for expansion 3
2024-10-13 12:16:24.920 +04:00 [INF] [AutoDuty] TrustHelper - Getting trust levels for expansion 4 from The Tower of Zot
2024-10-13 12:16:24.920 +04:00 [INF] [AutoDuty] Get Trust Levels: Level not set for: Estinien
2024-10-13 12:16:25.240 +04:00 [INF] [AutoDuty] TrustHelper - Done getting trust levels for expansion 4
2024-10-13 12:16:25.297 +04:00 [INF] [AutoDuty] Leveling Enabled
2024-10-13 12:16:25.297 +04:00 [INF] [AutoDuty] Leveling Trust Members set
2024-10-13 12:16:25.297 +04:00 [INF] [AutoDuty] 7
2024-10-13 12:16:25.297 +04:00 [INF] [AutoDuty] checking: Urianger
2024-10-13 12:16:25.297 +04:00 [INF] [AutoDuty] check successful
2024-10-13 12:16:25.297 +04:00 [INF] [AutoDuty] checking: Alphinaud
2024-10-13 12:16:25.297 +04:00 [INF] [AutoDuty] checking: Estinien
2024-10-13 12:16:25.297 +04:00 [INF] [AutoDuty] check successful
2024-10-13 12:16:25.297 +04:00 [INF] [AutoDuty] checking: Alisaie
2024-10-13 12:16:25.297 +04:00 [INF] [AutoDuty] checking: Thancred
2024-10-13 12:16:25.297 +04:00 [INF] [AutoDuty] check successful
2024-10-13 12:16:25.299 +04:00 [INF] [AutoDuty] Next Leveling Duty: The Tower of Zot
2024-10-13 12:16:26.975 +04:00 [INF] [MareSynchronos] [Player...actory]{2} Building character data for Player took 76.7725ms
2024-10-13 12:16:27.104 +04:00 [INF] [MareSynchronos] [Player...actory]{2} Building character data for MinionOrMount took 56.2274ms
2024-10-13 12:16:28.229 +04:00 [INF] [AutoDuty] AutoEquip - Started
2024-10-13 12:16:28.507 +04:00 [INF] [AutoDuty] AutoEquip Finished
2024-10-13 12:16:28.636 +04:00 [INF] [AutoDuty] Queueing: Trust: The Tower of Zot
```
softlocked after this line, closing the trust window will fix the issue for one run, then it will return. The only solution is to stop looping and restart it.

**Comment by erdelf** [comment]
odd, it wanted to slot in Estinien.. but your trust members in AD still show Ryne.
Odd that it doesn't slot in anyone though.

**Comment by K0shachiyamyatA** [comment]
> odd, it wanted to slot in Estinien.. but your trust members in AD still show Ryne. Odd that it doesn't slot in anyone though.

another random softlock with no one sloted in
```
2024-10-14 14:55:39.293 +04:00 [INF] [vnavmesh] Pathfinding complete
2024-10-14 14:55:42.852 +04:00 [INF] [AutoDuty] Starting Action Boss: Hermes
2024-10-14 14:56:36.837 +04:00 [INF] LASTEXCEPTION:eyJXaGVuIjoiMjAyNC0xMC0xNFQxNDo1NjozNi44Mzc0NTgrMDQ6MDAiLCJJbmZvIjoiU3lzdGVtLklPLklPRXhjZXB0aW9uOiBUaGUgcHJvY2VzcyBjYW5ub3QgYWNjZXNzIHRoZSBmaWxlICdDOlxcVXNlcnNcXHVzZXJcXEFwcERhdGFcXFJvYW1pbmdcXFhJVkxhdW5jaGVyXFxwbHVnaW5Db25maWdzXFxSb3RhdGlvblNvbHZlclxcSG9zdGlsZUNhc3RpbmdBcmVhLmpzb24nIGJlY2F1c2UgaXQgaXMgYmVpbmcgdXNlZCBieSBhbm90aGVyIHByb2Nlc3MuXHJcbiAgIGF0IE1pY3Jvc29mdC5XaW4zMi5TYWZlSGFuZGxlcy5TYWZlRmlsZUhhbmRsZS5DcmVhdGVGaWxlKFN0cmluZyBmdWxsUGF0aCwgRmlsZU1vZGUgbW9kZSwgRmlsZUFjY2VzcyBhY2Nlc3MsIEZpbGVTaGFyZSBzaGFyZSwgRmlsZU9wdGlvbnMgb3B0aW9ucylcclxuICAgYXQgTWljcm9zb2Z0LldpbjMyLlNhZmVIYW5kbGVzLlNhZmVGaWxlSGFuZGxlLk9wZW4oU3RyaW5nIGZ1bGxQYXRoLCBGaWxlTW9kZSBtb2RlLCBGaWxlQWNjZXNzIGFjY2VzcywgRmlsZVNoYXJlIHNoYXJlLCBGaWxlT3B0aW9ucyBvcHRpb25zLCBJbnQ2NCBwcmVhbGxvY2F0aW9uU2l6ZSwgTnVsbGFibGVgMSB1bml4Q3JlYXRlTW9kZSlcclxuICAgYXQgU3lzdGVtLklPLkZpbGUuV3JpdGVUb0ZpbGUoU3RyaW5nIHBhdGgsIEZpbGVNb2RlIG1vZGUsIFN0cmluZyBjb250ZW50cywgRW5jb2RpbmcgZW5jb2RpbmcpXHJcbiAgIGF0IFJvdGF0aW9uU29sdmVyLkJhc2ljLkNvbmZpZ3VyYXRpb24uT3RoZXJDb25maWd1cmF0aW9uLlNhdmVQYXRoW1RdKFQgdmFsdWUsIFN0cmluZyBwYXRoKSBpbiBEOlxcYVxcUm90YXRpb25Tb2x2ZXJSZWJvcm5cXFJvdGF0aW9uU29sdmVyUmVib3JuXFxSb3RhdGlvblNvbHZlci5CYXNpY1xcQ29uZmlndXJhdGlvblxcT3RoZXJDb25maWd1cmF0aW9uLmNzOmxpbmUgMTkxIiwiQ29udGV4dCI6IltSb3RhdGlvblNvbHZlcl0gRmFpbGVkIHRvIHNhdmUgdGhlIGZpbGUgdG8gQzpcXFVzZXJzXFx1c2VyXFxBcHBEYXRhXFxSb2FtaW5nXFxYSVZMYXVuY2hlclxccGx1Z2luQ29uZmlnc1xcUm90YXRpb25Tb2x2ZXJcXEhvc3RpbGVDYXN0aW5nQXJlYS5qc29uIn0=
2024-10-14 14:56:36.837 +04:00 [WRN] [RotationSolver] Failed to save the file to C:\Users\user\AppData\Roaming\XIVLauncher\pluginConfigs\RotationSolver\HostileCastingArea.json
System.IO.IOException: The process cannot access the file 'C:\Users\user\AppData\Roaming\XIVLauncher\pluginConfigs\RotationSolver\HostileCastingArea.json' because it is being used by another process.
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.File.WriteToFile(String path, FileMode mode, String contents, Encoding encoding)
   at RotationSolver.Basic.Configuration.OtherConfiguration.SavePath[T](T value, String path) in D:\a\RotationSolverReborn\RotationSolverReborn\RotationSolver.Basic\Configuration\OtherConfiguration.cs:line 191
2024-10-14 14:59:14.856 +04:00 [INF] LASTEXCEPTION:eyJXaGVuIjoiMjAyNC0xMC0xNFQxNDo1OToxNC44NTY5MTMxKzA0OjAwIiwiSW5mbyI6IlN5c3RlbS5JTy5JT0V4Y2VwdGlvbjogVGhlIHByb2Nlc3MgY2Fubm90IGFjY2VzcyB0aGUgZmlsZSAnQzpcXFVzZXJzXFx1c2VyXFxBcHBEYXRhXFxSb2FtaW5nXFxYSVZMYXVuY2hlclxccGx1Z2luQ29uZmlnc1xcUm90YXRpb25Tb2x2ZXJcXEhvc3RpbGVDYXN0aW5nQXJlYS5qc29uJyBiZWNhdXNlIGl0IGlzIGJlaW5nIHVzZWQgYnkgYW5vdGhlciBwcm9jZXNzLlxyXG4gICBhdCBNaWNyb3NvZnQuV2luMzIuU2FmZUhhbmRsZXMuU2FmZUZpbGVIYW5kbGUuQ3JlYXRlRmlsZShTdHJpbmcgZnVsbFBhdGgsIEZpbGVNb2RlIG1vZGUsIEZpbGVBY2Nlc3MgYWNjZXNzLCBGaWxlU2hhcmUgc2hhcmUsIEZpbGVPcHRpb25zIG9wdGlvbnMpXHJcbiAgIGF0IE1pY3Jvc29mdC5XaW4zMi5TYWZlSGFuZGxlcy5TYWZlRmlsZUhhbmRsZS5PcGVuKFN0cmluZyBmdWxsUGF0aCwgRmlsZU1vZGUgbW9kZSwgRmlsZUFjY2VzcyBhY2Nlc3MsIEZpbGVTaGFyZSBzaGFyZSwgRmlsZU9wdGlvbnMgb3B0aW9ucywgSW50NjQgcHJlYWxsb2NhdGlvblNpemUsIE51bGxhYmxlYDEgdW5peENyZWF0ZU1vZGUpXHJcbiAgIGF0IFN5c3RlbS5JTy5GaWxlLldyaXRlVG9GaWxlKFN0cmluZyBwYXRoLCBGaWxlTW9kZSBtb2RlLCBTdHJpbmcgY29udGVudHMsIEVuY29kaW5nIGVuY29kaW5nKVxyXG4gICBhdCBSb3RhdGlvblNvbHZlci5CYXNpYy5Db25maWd1cmF0aW9uLk90aGVyQ29uZmlndXJhdGlvbi5TYXZlUGF0aFtUXShUIHZhbHVlLCBTdHJpbmcgcGF0aCkgaW4gRDpcXGFcXFJvdGF0aW9uU29sdmVyUmVib3JuXFxSb3RhdGlvblNvbHZlclJlYm9yblxcUm90YXRpb25Tb2x2ZXIuQmFzaWNcXENvbmZpZ3VyYXRpb25cXE90aGVyQ29uZmlndXJhdGlvbi5jczpsaW5lIDE5MSIsIkNvbnRleHQiOiJbUm90YXRpb25Tb2x2ZXJdIEZhaWxlZCB0byBzYXZlIHRoZSBmaWxlIHRvIEM6XFxVc2Vyc1xcdXNlclxcQXBwRGF0YVxcUm9hbWluZ1xcWElWTGF1bmNoZXJcXHBsdWdpbkNvbmZpZ3NcXFJvdGF0aW9uU29sdmVyXFxIb3N0aWxlQ2FzdGluZ0FyZWEuanNvbiJ9
2024-10-14 14:59:14.856 +04:00 [WRN] [RotationSolver] Failed to save the file to C:\Users\user\AppData\Roaming\XIVLauncher\pluginConfigs\RotationSolver\HostileCastingArea.json
System.IO.IOException: The process cannot access the file 'C:\Users\user\AppData\Roaming\XIVLauncher\pluginConfigs\RotationSolver\HostileCastingArea.json' because it is being used by another process.
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.File.WriteToFile(String path, FileMode mode, String contents, Encoding encoding)
   at RotationSolver.Basic.Configuration.OtherConfiguration.SavePath[T](T value, String path) in D:\a\RotationSolverReborn\RotationSolverReborn\RotationSolver.Basic\Configuration\OtherConfiguration.cs:line 191
2024-10-14 14:59:48.154 +04:00 [INF] [AutoDuty] ExitDuty Started
2024-10-14 14:59:51.483 +04:00 [INF] [vnavmesh] Starting transition from 'ex4/01_nvt_n5/dun/n5d1/level/n5d1//3EFF5//0.0.0.0' to ''
2024-10-14 14:59:52.212 +04:00 [INF] [vnavmesh] Starting transition from '' to 'ffxiv/sea_s1/twn/s1t2/level/s1t2//11F3A//18.19.0.0'
2024-10-14 14:59:52.268 +04:00 [INF] [vnavmesh] Finishing transition to 'ffxiv/sea_s1/twn/s1t2/level/s1t2//11F3A//18.19.0.0'
2024-10-14 14:59:53.299 +04:00 [INF] [AutoDuty] ExitDuty Finished
2024-10-14 14:59:53.519 +04:00 [INF] [AutoDuty] TrustHelper - Getting trust levels for expansion 3 from Holminster Switch
2024-10-14 14:59:53.519 +04:00 [INF] [AutoDuty] Get Trust Levels: Level not set for: Alphinaud | Urianger
2024-10-14 14:59:53.727 +04:00 [WRN] PlayerTrack is accessing ObjectTable outside the main thread. This is deprecated.
2024-10-14 14:59:53.818 +04:00 [INF] [AutoDuty] TrustHelper - Done getting trust levels for expansion 3
2024-10-14 14:59:53.834 +04:00 [INF] [AutoDuty] TrustHelper - Getting trust levels for expansion 4 from The Tower of Zot
2024-10-14 14:59:53.834 +04:00 [INF] [AutoDuty] Get Trust Levels: Level not set for: Estinien
2024-10-14 14:59:54.152 +04:00 [INF] [AutoDuty] TrustHelper - Done getting trust levels for expansion 4
2024-10-14 14:59:54.208 +04:00 [INF] [AutoDuty] Leveling Enabled
2024-10-14 14:59:54.208 +04:00 [INF] [AutoDuty] Leveling Trust Members set
2024-10-14 14:59:54.208 +04:00 [INF] [AutoDuty] 7
2024-10-14 14:59:54.208 +04:00 [INF] [AutoDuty] checking: Urianger
2024-10-14 14:59:54.208 +04:00 [INF] [AutoDuty] check successful
2024-10-14 14:59:54.208 +04:00 [INF] [AutoDuty] checking: Alphinaud
2024-10-14 14:59:54.208 +04:00 [INF] [AutoDuty] checking: Estinien
2024-10-14 14:59:54.208 +04:00 [INF] [AutoDuty] check successful
2024-10-14 14:59:54.208 +04:00 [INF] [AutoDuty] checking: Alisaie
2024-10-14 14:59:54.208 +04:00 [INF] [AutoDuty] checking: Thancred
2024-10-14 14:59:54.208 +04:00 [INF] [AutoDuty] check successful
2024-10-14 14:59:54.212 +04:00 [INF] [AutoDuty] Next Leveling Duty: Ktisis Hyperboreia
2024-10-14 14:59:56.134 +04:00 [INF] [MareSynchronos] [Player...actory]{2} Building character data for MinionOrMount took 56.4736ms
2024-10-14 14:59:56.304 +04:00 [INF] [MareSynchronos] [Player...actory]{2} Building character data for Player took 77.5776ms
2024-10-14 14:59:57.155 +04:00 [INF] [AutoDuty] AutoEquip - Started
2024-10-14 14:59:57.434 +04:00 [INF] [AutoDuty] AutoEquip Finished
2024-10-14 14:59:57.525 +04:00 [INF] [AutoDuty] Leveling Trust Members set
2024-10-14 14:59:57.525 +04:00 [INF] [AutoDuty] 8
2024-10-14 14:59:57.525 +04:00 [INF] [AutoDuty] checking: Krile
2024-10-14 14:59:57.525 +04:00 [INF] [AutoDuty] check successful
2024-10-14 14:59:57.525 +04:00 [INF] [AutoDuty] checking: Urianger
2024-10-14 14:59:57.525 +04:00 [INF] [AutoDuty] check successful
2024-10-14 14:59:57.525 +04:00 [INF] [AutoDuty] checking: Alphinaud
2024-10-14 14:59:57.525 +04:00 [INF] [AutoDuty] checking: Estinien
2024-10-14 14:59:57.525 +04:00 [INF] [AutoDuty] checking: Alisaie
2024-10-14 14:59:57.525 +04:00 [INF] [AutoDuty] checking: Thancred
2024-10-14 14:59:57.525 +04:00 [INF] [AutoDuty] check successful
2024-10-14 14:59:57.569 +04:00 [INF] [AutoDuty] Queueing: Trust: Ktisis Hyperboreia
```

**Comment by K0shachiyamyatA** [comment]
i restarted the plagin and now it queues worqor zormor so it's a bug too, then

**Comment by Herculezz55** [comment]
still happening?

**Comment by ThisIsNoTa2acc** [comment]
> still happening?

Didn't test since then

**Comment by K0shachiyamyatA** [comment]
> still happening?

Didn't test since then

**Comment by K0shachiyamyatA** [comment]
well at least now it works for healers, tanks and ranged physical/magical dps. only didn't test melee yet. i'll close this for now if the bug will happen again i'll reopen this issue

**Comment by K0shachiyamyatA** [comment]
![Screenshot_20250106_011728_AnyDesk](https://github.com/user-attachments/assets/8b3406a0-66af-469f-9fd1-b6a695e995d0)
It happened again. On sage, specifically

**Comment by erdelf** [comment]
well the code got changed two times over since this issue. Still happening?

**Comment by K0shachiyamyatA** [comment]
Can't say i can replicate it right now. If it was changed, maybe we should consider this closed until proven otherwise.
