### ISSUE TITLE
[Bug] Trust mode didn`t move to dungeon

### ISSUE THREAD

**Issue by sparrowprime** [ffxivcode/AutoDuty#622]
### What happened?

press run and didn`t happend anything
![图片](https://github.com/user-attachments/assets/8adfb809-d560-495b-b04d-fe8869da6749)

by the way, it can move to dungeon after i do this
[run, chose duty by my self, move in dungeon, quit dungeon]
it logs just after error logs

### Version Number

173

### Steps to reproduce the error

just press run?
i just try trust mode

### Relevant log output

```shell
14:16:46.589 | INF | [AutoDuty] Running AutoDuty in 异形楼阁佐特塔, Looping 1 times
14:16:46.589 | ERR | [WindowSystem] Error during Draw(): AutoDuty v0.0.0.173###Autoduty
	System.NullReferenceException: Object reference not set to an instance of an object.
	   at Dalamud.Plugin.Ipc.Internal.CallGateChannel.InvokeFunc[TRet](Object[] args)
	   at Dalamud.Plugin.Ipc.Internal.CallGatePubSub`2.InvokeFunc(T1 arg1)
	   at ECommons.EzIpcManager.SafeWrapperIPC.Wrapper`2.InvokeFunction(T1 a1) in /home/runner/work/AutoDuty/AutoDuty/ECommons/ECommons/EzIpcManager/SafeWrapperIPC.cs:line 247
	   at AutoDuty.AutoDuty.GetGeneralSettings() in /home/runner/work/AutoDuty/AutoDuty/AutoDuty/AutoDuty.cs:line 1137
	   at AutoDuty.AutoDuty.SetGeneralSettings(Boolean on) in /home/runner/work/AutoDuty/AutoDuty/AutoDuty/AutoDuty.cs:line 1147
	   at AutoDuty.AutoDuty.Run(UInt32 territoryType, Int32 loops, Boolean startFromZero, Boolean bareMode) in /home/runner/work/AutoDuty/AutoDuty/AutoDuty/AutoDuty.cs:line 514
	   at AutoDuty.Windows.MainTab.Draw() in /home/runner/work/AutoDuty/AutoDuty/AutoDuty/Windows/MainTab.cs:line 213
	   at AutoDuty.Windows.MainWindow.EzTabBar(String id, String KoFiTransparent, String openTabName, ImGuiTabBarFlags flags, ValueTuple`4[] tabs) in /home/runner/work/AutoDuty/AutoDuty/AutoDuty/Windows/MainWindow.cs:line 388
	   at AutoDuty.Windows.MainWindow.Draw() in /home/runner/work/AutoDuty/AutoDuty/AutoDuty/Windows/MainWindow.cs:line 410
	   at Dalamud.Interface.Windowing.Window.DrawInternal(DalamudConfiguration configuration)
14:21:07.012 | INF | [vnavmesh] 开始从 'ffxiv/roc_r1/hou/r1h1/level/r1h1//3F586//18.19.8E.0' 转换至 ''
14:21:07.666 | INF | [vnavmesh] 开始从 '' 转换至 'ex4/02_mid_m5/dun/m5d2/level/m5d2//3EF2A//0.0.0.0'
14:21:07.721 | INF | [vnavmesh] 完成向 'ex4/02_mid_m5/dun/m5d2/level/m5d2//3EF2A//0.0.0.0' 的转换
14:21:20.011 | INF | [vnavmesh] 开始从 'ex4/02_mid_m5/dun/m5d2/level/m5d2//3EF2A//0.0.0.0' 转换至 ''
14:21:20.419 | INF | [vnavmesh] 开始从 '' 转换至 'ffxiv/roc_r1/hou/r1h1/level/r1h1//3F586//18.19.8E.0'
14:21:20.487 | INF | [vnavmesh] 完成向 'ffxiv/roc_r1/hou/r1h1/level/r1h1//3F586//18.19.8E.0' 的转换
14:21:21.786 | INF | [AutoDuty] Leveling Trust Members set
14:21:21.786 | INF | [AutoDuty] 7
14:21:21.786 | INF | [AutoDuty] checking: 古·拉哈·提亚
14:21:21.786 | INF | [AutoDuty] check successful
14:21:21.786 | INF | [AutoDuty] checking: 于里昂热
14:21:21.786 | INF | [AutoDuty] check successful
14:21:21.786 | INF | [AutoDuty] checking: 雅·修特拉
14:21:21.786 | INF | [AutoDuty] check successful
14:21:22.015 | INF | [AutoDuty] TrustHelper - Getting trust levels for expansion 3 from 遇袭集落水滩村
14:21:22.015 | INF | [AutoDuty] Get Trust Levels: Level not set for: 阿尔菲诺 | 阿莉塞 | 桑克瑞德 | 于里昂热 | 雅·修特拉 | 古·拉哈·提亚
14:21:22.251 | INF | [AutoDuty] TrustHelper - Done getting trust levels for expansion 3
14:21:22.259 | INF | [AutoDuty] TrustHelper - Getting trust levels for expansion 4 from 异形楼阁佐特塔
14:21:22.259 | INF | [AutoDuty] Get Trust Levels: Level not set for: 埃斯蒂尼安
14:21:22.586 | INF | [AutoDuty] TrustHelper - Done getting trust levels for expansion 4
14:21:22.642 | INF | [AutoDuty] Leveling Enabled
14:21:22.642 | INF | [AutoDuty] Leveling Trust Members set
14:21:22.642 | INF | [AutoDuty] 7
14:21:22.642 | INF | [AutoDuty] checking: 古·拉哈·提亚
14:21:22.642 | INF | [AutoDuty] check successful
14:21:22.642 | INF | [AutoDuty] checking: 于里昂热
14:21:22.642 | INF | [AutoDuty] check successful
14:21:22.642 | INF | [AutoDuty] checking: 雅·修特拉
14:21:22.642 | INF | [AutoDuty] check successful
14:21:22.653 | INF | [AutoDuty] Next Leveling Duty: 异形楼阁佐特塔
14:21:22.716 | INF | [AutoDuty] Queueing: Trust: 异形楼阁佐特塔
14:21:25.644 | WRN | [HITCH] Long "GameNetworkDown" detected, 31.2229ms > 30ms - check in the plugin stats window.
14:21:25.654 | INF | [vnavmesh] 开始从 'ffxiv/roc_r1/hou/r1h1/level/r1h1//3F586//18.19.8E.0' 转换至 ''
14:21:25.655 | INF | [AutoDuty] Done Queueing: Trust: 异形楼阁佐特塔
14:21:26.412 | INF | [vnavmesh] 开始从 '' 转换至 'ex4/02_mid_m5/dun/m5d1/level/m5d1//3EB80//0.0.0.0'
14:21:26.465 | INF | [vnavmesh] 完成向 'ex4/02_mid_m5/dun/m5d1/level/m5d1//3EB80//0.0.0.0' 的转换
14:21:32.005 | INF | [AutoDuty] Starting Navigation
14:21:32.018 | INF | [vnavmesh] Queueing move-to <68.400, -442.970, -124.130>
14:21:32.047 | INF | [vnavmesh] Pathfinding complete
```

**Comment by erdelf** [comment]
Do you have a custom fork of Pandora's Box or something? The bug is that it detects Pandora's Box as active, but can't talk to it properly.

**Comment by sparrowprime** [comment]
aaaa, yes, i acutlly have pandora, i closed it and it`s ok, but why...
