### ISSUE TITLE
[Bug] /ad queue can get stuck on outdated addon instance & will break until reloading the plugin

### ISSUE THREAD

**Issue by carvelli** [ffxivcode/AutoDuty#629]
### What happened?

I'm using a SND script that, at some point, uses `/ad queue The Praetorium`

However, it seems with the way this is coded, it's likely that in https://github.com/ffxivcode/AutoDuty/blob/9c987b5ac9a56c46b1f02ba2f17d75b21bb6f06e/AutoDuty/Helpers/QueueHelper.cs#L176, `_allConditionsMetToJoin` is true (possibly from a previous successful attempt to queue into an instance), and will at that point no longer call `TryGetAddonByName` to update the addon reference at all, thus any further attempts after this will produce the exception below.

Reloading the plugin fixes that error, it's just inconvenient to troubleshoot.

### Version Number

0.0.0.173

### Steps to reproduce the error

Be in a party with someone else

- /ad queue The Praetorium
- other person cancels (or doesn't accept) the duty prompt, so you don't end up in the instance
- /ad queue is broken afterwards, regardless of which duty you select

### Relevant log output

```shell
System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at AutoDuty.Helpers.QueueHelper.QueueRegular() in /home/runner/work/AutoDuty/AutoDuty/AutoDuty/Helpers/QueueHelper.cs:line 183
   at AutoDuty.Helpers.QueueHelper.QueueUpdate(IFramework _) in /home/runner/work/AutoDuty/AutoDuty/AutoDuty/Helpers/QueueHelper.cs:line 236
   at Dalamud.Utility.EventHandlerExtensions.HandleInvoke(Action act) in C:\goatsoft\companysecrets\dalamud\\Utility\EventHandlerExtensions.cs:line 124
```

**Comment by erdelf** [comment]
fixed in https://github.com/ffxivcode/AutoDuty/pull/828
