### ISSUE TITLE
[Bug] Dalamud crash at the start

### ISSUE THREAD

**Issue by SuspiciousActivity** [ffxivcode/AutoDuty#693]
### What happened?

Sometimes I get an error message saying Dalamud crashed and needs to restart, the problem is caused by AutoDuty.
It looks like a race condition, https://github.com/ffxivcode/AutoDuty/blob/3c2fdd3cae36d8f7b7e87314e2797e7b07082979/AutoDuty/Updater/FileHelper.cs#L108 and https://github.com/ffxivcode/AutoDuty/blob/3c2fdd3cae36d8f7b7e87314e2797e7b07082979/AutoDuty/Updater/FileHelper.cs#L109 are sometimes running at the same time, because it's called once from Init() and also once from the FileSystemWatcher (two different threads).
This should be an easy fix by adding a lock around the Update() function, so only one thread can access the dictionary at the same time.

### Version Number

v0.0.0.179

### Steps to reproduce the error

Start the game (only happens sometimes)

### Relevant log output

```shell
2024-12-06 08:42:06.815 +01:00 [INF] [AutoDuty] Failed loading plugin
System.ArgumentException: An item with the same key has already been added. Key: 1037
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at AutoDuty.Updater.FileHelper.Update() in /home/runner/work/AutoDuty/AutoDuty/AutoDuty/Updater/FileHelper.cs:line 109
   at AutoDuty.Updater.FileHelper.Init() in /home/runner/work/AutoDuty/AutoDuty/AutoDuty/Updater/FileHelper.cs:line 91
   at AutoDuty.AutoDuty..ctor() in /home/runner/work/AutoDuty/AutoDuty/AutoDuty/AutoDuty.cs:line 223


2024-12-06 08:42:06.820 +01:00 [FTL] Unhandled exception on AppDomain
System.InvalidOperationException: Operations that change non-concurrent collections must have exclusive access. A concurrent update was performed on this collection and corrupted its state. The collection's state is no longer correct.
   at System.Collections.Generic.Dictionary`2.FindValue(TKey key)
   at AutoDuty.Updater.FileHelper.Update() in /home/runner/work/AutoDuty/AutoDuty/AutoDuty/Updater/FileHelper.cs:line 108
   at System.IO.FileSystemWatcher.NotifyFileSystemEventArgs(WatcherChangeTypes changeType, ReadOnlySpan`1 name)
   at System.IO.FileSystemWatcher.ParseEventBufferAndNotifyForEach(ReadOnlySpan`1 buffer)
   at System.IO.FileSystemWatcher.ReadDirectoryChangesCallback(UInt32 errorCode, UInt32 numBytes, AsyncReadState state)
   at System.IO.FileSystemWatcher.<>c.<StartRaisingEvents>b__85_0(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* overlappedPointer)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
```

### Other relevant plugins installed

Maybe JustBackup?

**Comment by erdelf** [comment]
I am honestly astonished you manage to regularly poke the file watcher in the exact moment the startup is running...

**Comment by erdelf** [comment]
added the lock in https://github.com/ffxivcode/AutoDuty/commit/2c29b232bb65324218768d37404a39c327be2a3c
a commit with a stunningly badly done diff by github..
